version: '3.1'

services:

  # NginX Server for the dashboard frontend static content
  # This uses minimal NginX configuration from ./nginx.conf. 
  # TODO: Add config to cache static assets (images, css...)
  # TODO: Expose nginx logs?
  web:
    container_name: cumulus-dashboard-frontend
    build: ./nginx
    ports:
      - $FRONTEND_PORT:80
    volumes:
      - ./app/build:/usr/share/nginx/html 
    depends_on:
      - api

  api:
    container_name: cumulus-dashboard-backend
    build: ./app/
    ports:
      - $BACKEND_PORT:80
    depends_on:
      - db
    # TODO: we may be able to replace this with new envfile loading
    # https://github.com/docker/compose/issues/7326
    environment:
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_DATABASE=$DB_DATABASE
      - DB_SYNC=$DB_SYNC
      - DB_SEED=$DB_SEED
      - DB_SSL=$DB_SSL
      - DATABASE_URL=postgres://$DB_USER:$DB_PASS@db:$DB_PORT/$DB_DATABASE
      - NODE_ENV=$NODE_ENV
      - PORT=80
      - REACT_APP_BACKEND_HOST=http://localhost:4001
      - MAILGUN_API_KEY=$MAILGUN_API_KEY
      - MAILGUN_DOMAIN=$MAILGUN_DOMAIN
      - THROTTLE=$THROTTLE
    volumes:
      - ./app/backend:/app/backend
      - ./app/build:/app/build
      - ./app/logs:/app/logs
      - ./app/src:/app/src      
      - ./app/public:/app/public   
    depends_on:
      - db   

  db:
    container_name: cumulus-dashboard-db
    image: postgres:14
    restart: on-failure
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DATABASE
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGPORT=$DB_PORT
    volumes:
      - ./postgres/sql:/docker-entrypoint-initdb.d
      - cumulus-dashboard-db-data:/var/lib/postgresql/data/pgdata
volumes:
   cumulus-dashboard-db-data:
