export default [
    
    // Subscription Groups
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscription Groups", action: "read"  , resource_id: null, permission: 1, comment: "Can read subscription groups"   },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscription Groups", action: "create", resource_id: null, permission: 1, comment: "Can create subscription groups" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscription Groups", action: "update", resource_id: null, permission: 1, comment: "Can update subscription groups" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscription Groups", action: "delete", resource_id: null, permission: 1, comment: "Can delete subscription groups" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscription Groups", action: "read"  , resource_id: null, permission: 1, comment: "Can read subscription groups"   },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscription Groups", action: "create", resource_id: null, permission: 1, comment: "Can create subscription groups" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscription Groups", action: "update", resource_id: null, permission: 1, comment: "Can update subscription groups" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscription Groups", action: "delete", resource_id: null, permission: 1, comment: "Can delete subscription groups" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscription Groups", action: "read"  , resource_id: null, permission: 1, comment: "Can read subscription groups"   },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscription Groups", action: "create", resource_id: null, permission: 0, comment: "Can create subscription groups" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscription Groups", action: "update", resource_id: null, permission: 0, comment: "Can update subscription groups" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscription Groups", action: "delete", resource_id: null, permission: 0, comment: "Can delete subscription groups" },
    
    // Graphs
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Graphs", action: "read"  , resource_id: null, permission: 1, comment: "Can read graphs"   },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Graphs", action: "create", resource_id: null, permission: 1, comment: "Can create graphs" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Graphs", action: "update", resource_id: null, permission: 1, comment: "Can update graphs" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Graphs", action: "delete", resource_id: null, permission: 1, comment: "Can delete graphs" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Graphs", action: "read"  , resource_id: null, permission: 1, comment: "Can read graphs"   },
    { user_id: null, role: "manager", user_group_id: null, resource: "Graphs", action: "create", resource_id: null, permission: 1, comment: "Can create graphs" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Graphs", action: "update", resource_id: null, permission: 1, comment: "Can update graphs" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Graphs", action: "delete", resource_id: null, permission: 1, comment: "Can delete graphs" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Graphs", action: "read"  , resource_id: null, permission: 0, comment: "Can read graphs"   },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Graphs", action: "create", resource_id: null, permission: 0, comment: "Can create graphs" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Graphs", action: "update", resource_id: null, permission: 0, comment: "Can update graphs" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Graphs", action: "delete", resource_id: null, permission: 0, comment: "Can delete graphs" },

    // DataRequests
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscriptions", action: "read"                 , resource_id: null, permission: 1, comment: "Can read subscriptions"                         },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscriptions", action: "create"               , resource_id: null, permission: 1, comment: "Can create subscriptions"                       },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscriptions", action: "update"               , resource_id: null, permission: 1, comment: "Can update subscriptions"                       },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscriptions", action: "delete"               , resource_id: null, permission: 1, comment: "Can delete subscriptions"                       },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscriptions", action: "export"               , resource_id: null, permission: 1, comment: "Can export subscriptions data"                  },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscriptions", action: "refresh"              , resource_id: null, permission: 1, comment: "Can refresh subscriptions data"                 },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscriptions", action: "requestLineLevelData" , resource_id: null, permission: 1, comment: "Can request line-level data from subscriptions" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscriptions", action: "read"                 , resource_id: null, permission: 1, comment: "Can read subscriptions"                         },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscriptions", action: "create"               , resource_id: null, permission: 1, comment: "Can create subscriptions"                       },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscriptions", action: "update"               , resource_id: null, permission: 1, comment: "Can update subscriptions"                       },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscriptions", action: "delete"               , resource_id: null, permission: 1, comment: "Can delete subscriptions"                       },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscriptions", action: "export"               , resource_id: null, permission: 1, comment: "Can export subscriptions data"                  },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscriptions", action: "refresh"              , resource_id: null, permission: 0, comment: "Can refresh subscriptions data"                 },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscriptions", action: "requestLineLevelData" , resource_id: null, permission: 1, comment: "Can request line-level data from subscriptions" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscriptions", action: "read"                 , resource_id: null, permission: 1, comment: "Can read subscriptions"                         },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscriptions", action: "create"               , resource_id: null, permission: 0, comment: "Can create subscriptions"                       },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscriptions", action: "update"               , resource_id: null, permission: 0, comment: "Can update subscriptions"                       },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscriptions", action: "delete"               , resource_id: null, permission: 0, comment: "Can delete subscriptions"                       },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscriptions", action: "export"               , resource_id: null, permission: 1, comment: "Can export subscriptions data"                  },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscriptions", action: "refresh"              , resource_id: null, permission: 0, comment: "Can refresh subscriptions data"                 },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscriptions", action: "requestLineLevelData" , resource_id: null, permission: 1, comment: "Can request line-level data from subscriptions" },
    
    // DataSites
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Data Sites", action: "read"  , resource_id: null, permission: 1, comment: "Can read sites"   },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Data Sites", action: "create", resource_id: null, permission: 1, comment: "Can create sites" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Data Sites", action: "update", resource_id: null, permission: 1, comment: "Can update sites" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Data Sites", action: "delete", resource_id: null, permission: 1, comment: "Can delete sites" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Data Sites", action: "read"  , resource_id: null, permission: 1, comment: "Can read sites"   },
    { user_id: null, role: "manager", user_group_id: null, resource: "Data Sites", action: "create", resource_id: null, permission: 1, comment: "Can create sites" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Data Sites", action: "update", resource_id: null, permission: 1, comment: "Can update sites" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Data Sites", action: "delete", resource_id: null, permission: 0, comment: "Can delete sites" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Data Sites", action: "read"  , resource_id: null, permission: 1, comment: "Can read sites"   },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Data Sites", action: "create", resource_id: null, permission: 0, comment: "Can create sites" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Data Sites", action: "update", resource_id: null, permission: 0, comment: "Can update sites" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Data Sites", action: "delete", resource_id: null, permission: 0, comment: "Can delete sites" },
          
    // Projects
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Study Areas", action: "read"  , resource_id: null, permission: 1, comment: "Can read study areas"   },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Study Areas", action: "create", resource_id: null, permission: 1, comment: "Can create study areas" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Study Areas", action: "update", resource_id: null, permission: 1, comment: "Can update study areas" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Study Areas", action: "delete", resource_id: null, permission: 1, comment: "Can delete study areas" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Study Areas", action: "read"  , resource_id: null, permission: 1, comment: "Can read study areas"   },
    { user_id: null, role: "manager", user_group_id: null, resource: "Study Areas", action: "create", resource_id: null, permission: 1, comment: "Can create study areas" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Study Areas", action: "update", resource_id: null, permission: 1, comment: "Can update study areas" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Study Areas", action: "delete", resource_id: null, permission: 1, comment: "Can delete study areas" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Study Areas", action: "read"  , resource_id: null, permission: 1, comment: "Can read study areas"   },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Study Areas", action: "create", resource_id: null, permission: 0, comment: "Can create study areas" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Study Areas", action: "update", resource_id: null, permission: 0, comment: "Can update study areas" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Study Areas", action: "delete", resource_id: null, permission: 0, comment: "Can delete study areas" },

    // Users
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Users", action: "read"  , resource_id: null, permission: 1, comment: "Can read users"         },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Users", action: "create", resource_id: null, permission: 1, comment: "Can create users"       },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Users", action: "update", resource_id: null, permission: 1, comment: "Can update users"       },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Users", action: "delete", resource_id: null, permission: 1, comment: "Can delete users"       },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Users", action: "invite", resource_id: null, permission: 1, comment: "Can invite other users" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Users", action: "read"  , resource_id: null, permission: 0, comment: "Can read users"         },
    { user_id: null, role: "manager", user_group_id: null, resource: "Users", action: "create", resource_id: null, permission: 0, comment: "Can create users"       },
    { user_id: null, role: "manager", user_group_id: null, resource: "Users", action: "update", resource_id: null, permission: 0, comment: "Can update users"       },
    { user_id: null, role: "manager", user_group_id: null, resource: "Users", action: "delete", resource_id: null, permission: 0, comment: "Can delete users"       },
    { user_id: null, role: "manager", user_group_id: null, resource: "Users", action: "invite", resource_id: null, permission: 0, comment: "Can invite other users" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Users", action: "read"  , resource_id: null, permission: 0, comment: "Can read users"         },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Users", action: "create", resource_id: null, permission: 0, comment: "Can create users"       },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Users", action: "update", resource_id: null, permission: 0, comment: "Can update users"       },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Users", action: "delete", resource_id: null, permission: 0, comment: "Can delete users"       },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Users", action: "invite", resource_id: null, permission: 0, comment: "Can invite other users" },

    // Tags
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Tags" , action: "read"  , resource_id: null, permission: 1, comment: "Can read tags"   },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Tags" , action: "create", resource_id: null, permission: 1, comment: "Can create tags" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Tags" , action: "update", resource_id: null, permission: 1, comment: "Can update tags" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Tags" , action: "delete", resource_id: null, permission: 1, comment: "Can delete tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Tags" , action: "read"  , resource_id: null, permission: 1, comment: "Can read tags"   },
    { user_id: null, role: "manager", user_group_id: null, resource: "Tags" , action: "create", resource_id: null, permission: 1, comment: "Can create tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Tags" , action: "update", resource_id: null, permission: 1, comment: "Can update tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Tags" , action: "delete", resource_id: null, permission: 1, comment: "Can delete tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Tags" , action: "read"  , resource_id: null, permission: 1, comment: "Can read tags"   },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Tags" , action: "create", resource_id: null, permission: 0, comment: "Can create tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Tags" , action: "update", resource_id: null, permission: 0, comment: "Can update tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Tags" , action: "delete", resource_id: null, permission: 0, comment: "Can delete tags" },
    
    // DataRequestsTags
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscription Tags", action: "read"  , resource_id: null, permission: 1, comment: "Can read subscription tags"   },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscription Tags", action: "create", resource_id: null, permission: 1, comment: "Can create subscription tags" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscription Tags", action: "update", resource_id: null, permission: 1, comment: "Can update subscription tags" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Subscription Tags", action: "delete", resource_id: null, permission: 1, comment: "Can delete subscription tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscription Tags", action: "read"  , resource_id: null, permission: 1, comment: "Can read subscription tags"   },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscription Tags", action: "create", resource_id: null, permission: 0, comment: "Can create subscription tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscription Tags", action: "update", resource_id: null, permission: 0, comment: "Can update subscription tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Subscription Tags", action: "delete", resource_id: null, permission: 0, comment: "Can delete subscription tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscription Tags", action: "read"  , resource_id: null, permission: 1, comment: "Can read subscription tags"   },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscription Tags", action: "create", resource_id: null, permission: 0, comment: "Can create subscription tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscription Tags", action: "update", resource_id: null, permission: 0, comment: "Can update subscription tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Subscription Tags", action: "delete", resource_id: null, permission: 0, comment: "Can delete subscription tags" },

    // ViewsTags
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Graph Tags", action: "read"  , resource_id: null, permission: 1, comment: "Can read graph tags"   },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Graph Tags", action: "create", resource_id: null, permission: 1, comment: "Can create graph tags" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Graph Tags", action: "update", resource_id: null, permission: 1, comment: "Can update graph tags" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Graph Tags", action: "delete", resource_id: null, permission: 1, comment: "Can delete graph tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Graph Tags", action: "read"  , resource_id: null, permission: 1, comment: "Can read graph tags"   },
    { user_id: null, role: "manager", user_group_id: null, resource: "Graph Tags", action: "create", resource_id: null, permission: 1, comment: "Can create graph tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Graph Tags", action: "update", resource_id: null, permission: 1, comment: "Can update graph tags" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Graph Tags", action: "delete", resource_id: null, permission: 1, comment: "Can delete graph tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Graph Tags", action: "read"  , resource_id: null, permission: 1, comment: "Can read graph tags"   },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Graph Tags", action: "create", resource_id: null, permission: 0, comment: "Can create graph tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Graph Tags", action: "update", resource_id: null, permission: 0, comment: "Can update graph tags" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Graph Tags", action: "delete", resource_id: null, permission: 0, comment: "Can delete graph tags" },

    // ProjectsSubscriptions
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Study Area Subscriptions", action: "read"  , resource_id: null, permission: 1, comment: "Can read which subscriptions are included in study area"   },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Study Area Subscriptions", action: "create", resource_id: null, permission: 1, comment: "Can add subscriptions to study area"                       },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Study Area Subscriptions", action: "update", resource_id: null, permission: 1, comment: "Can update which subscriptions are included in study area" },
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Study Area Subscriptions", action: "delete", resource_id: null, permission: 1, comment: "Can exclude subscriptions from study area"                 },
    { user_id: null, role: "manager", user_group_id: null, resource: "Study Area Subscriptions", action: "read"  , resource_id: null, permission: 1, comment: "Can read which subscriptions are included in study area"   },
    { user_id: null, role: "manager", user_group_id: null, resource: "Study Area Subscriptions", action: "create", resource_id: null, permission: 1, comment: "Can add subscriptions to study area"                       },
    { user_id: null, role: "manager", user_group_id: null, resource: "Study Area Subscriptions", action: "update", resource_id: null, permission: 1, comment: "Can update which subscriptions are included in study area" },
    { user_id: null, role: "manager", user_group_id: null, resource: "Study Area Subscriptions", action: "delete", resource_id: null, permission: 1, comment: "Can exclude subscriptions from study area"                 },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Study Area Subscriptions", action: "read"  , resource_id: null, permission: 1, comment: "Can read which subscriptions are included in study area"   },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Study Area Subscriptions", action: "create", resource_id: null, permission: 0, comment: "Can add subscriptions to study area"                       },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Study Area Subscriptions", action: "update", resource_id: null, permission: 0, comment: "Can update which subscriptions are included in study area" },
    { user_id: null, role: "user"   , user_group_id: null, resource: "Study Area Subscriptions", action: "delete", resource_id: null, permission: 0, comment: "Can exclude subscriptions from study area"                 },

    // Logs
    { user_id: null, role: "admin"  , user_group_id: null, resource: "Logs", action: "read", resource_id: null, permission: 1, comment: "Can read logs" },

    // Permissions
    { user_id: null, role: "admin"  , resource: "Permissions", action: "read"  , user_group_id: null, resource_id : null, permission: 1,                          comment: "Can read permissions" },
    { user_id: null, role: "admin"  , resource: "Permissions", action: "update", user_group_id: null, resource_id : null, permission: 1, attribute: "permission", comment: "Can flip permissions" },
]
