
/**
 * @param {import("sequelize").Sequelize} DB
 */
module.exports = async ({ models }) => {

    await models.User.bulkCreate([
        {
            id      : 1,
            role    : "user",
            username: "user1",
            password: "user1password"
        },
        {
            id      : 2,
            role    : "user",
            username: "user2",
            password: "user2password"
        },
        {
            id      : 3,
            role    : "admin",
            username: "admin1",
            password: "admin1password"
        },
        {
            id      : 4,
            role    : "admin",
            username: "admin2",
            password: "admin2password"
        }
    ]);

    await models.RequestGroup.bulkCreate([
        { id: 1, name: "GENERAL"   },
        { id: 2, name: "COVID-19"  },
        { id: 3, name: "INFLUENZA" },
        { id: 4, name: "HIV"       },
    ]);

    await models.DataRequest.bulkCreate([

        {
            id: 1,
            name: "COVID Dataset 1",
            // description: "",
            groupId: 2,
            refresh: "monthly"
        },
        {
            id: 2,
            name: "COVID Dataset 2",
            groupId: 2,
            refresh: "weekly",
            // completed: null,
        },
        {
            id: 3,
            name: "COVID Dataset 3",
            groupId: 2,
            // refresh: "manually",
            // completed: "2022-02-01",
        },
        {
            id: 4,
            name: "INFLUENZA Dataset 1",
            groupId: 3,
            // refresh: "daily",
            // completed: "2022-02-01",
        },
        {
            id: 5,
            name: "HIV Dataset 1",
            groupId: 4,
            refresh: "weekly",
            // completed: null,
        },
        {
            id: 6,
            name: "Patient Age and Gender",
            groupId: 1,
            refresh: "monthly",
            completed: "2022-02-02",
            data: {
                cols: [
                    {
                        name: "age",
                        label: "Patient Age in Years",
                        description: "Patient Age in Years",
                        dataType: "integer"
                    },
                    {
                        name: "gender",
                        label: "Patient Gender",
                        description: "Patient Gender",
                        dataType: "string"
                    },
                    {
                        name: "cnt",
                        label: "Count",
                        description: "Count",
                        dataType: "integer"
                    }
                ],
                rows: [
                    [3, null, 13 ],
                    [6, null, 11 ],
                    [8, null, 12 ],
                    [9, null, 14 ],
                    [11, null, 14 ],
                    [14, null, 16 ],
                    [16,"male", 17 ],
                    [16, null, 22 ],
                    [17,"female", 15 ],
                    [17, null, 24 ],
                    [18, null, 14 ],
                    [21, null, 15 ],
                    [22, null, 11 ],
                    [23,"female", 12 ],
                    [23, null, 18 ],
                    [24,"female", 12 ],
                    [24, null, 19 ],
                    [26, null, 13 ],
                    [27,"male", 13 ],
                    [27, null, 19 ],
                    [28,"male", 13 ],
                    [28, null, 20 ],
                    [29, null, 16 ],
                    [30,"male", 12 ],
                    [30, null, 20 ],
                    [32, null, 11 ],
                    [33, null, 11 ],
                    [35,"male", 15 ],
                    [35, null, 24 ],
                    [36,"female", 13 ],
                    [36, null, 17 ],
                    [38,"female", 15 ],
                    [38, null, 17 ],
                    [39, null, 13 ],
                    [40, null, 14 ],
                    [41, null, 14 ],
                    [42, null, 15 ],
                    [43, null, 14 ],
                    [44, null, 11 ],
                    [45, null, 14 ],
                    [46,"male", 12 ],
                    [46, null, 19 ],
                    [47, null, 14 ],
                    [48, null, 17 ],
                    [49, null, 13 ],
                    [50,"female", 11 ],
                    [50, null, 17 ],
                    [51, null, 19 ],
                    [52,"female", 12 ],
                    [52,"male", 11 ],
                    [52, null, 23 ],
                    [53, null, 15 ],
                    [54, null, 16 ],
                    [55, null, 15 ],
                    [56, null, 15 ],
                    [57, null, 17 ],
                    [58, null, 11 ],
                    [59, null, 12 ],
                    [60,"female", 12 ],
                    [60,"male", 18 ],
                    [60, null, 30 ],
                    [61, null, 12 ],
                    [62,"female", 11 ],
                    [62, null, 17 ],
                    [63,"female", 11 ],
                    [63, null, 16 ],
                    [64,"male", 13 ],
                    [64, null, 23 ],
                    [65, null, 11 ],
                    [66, null, 12 ],
                    [68,"female", 11 ],
                    [68, null, 19 ],
                    [69, null, 14 ],
                    [70,"male", 15 ],
                    [70, null, 17 ],
                    [76, null, 14 ],
                    [82, null, 13 ],
                    [null,"female", 568 ],
                    [null,"male", 31 ],
                    [null,"male", 583 ],
                    [null, null, 1151 ],
                    [null, null, 39 ]
                ]
            }
        },
        {
            id: 7,
            name: "Data for Newborns",
            groupId: 1,
            refresh: null,
            completed: "2022-02-02",
            data: {
                cols: [
                    {
                        name: "age",
                        label: "Age",
                        description: "Patient age",
                        dataType: "string"
                    },
                    {
                        name: "age_group",
                        label: "Age Group",
                        description: "Age group as defined by CDC",
                        dataType: "string"
                    },
                    {
                        name: "gender",
                        label: "Gender",
                        description: "",
                        dataType: "string"
                    },
                    {
                        name: "race",
                        label: "Race",
                        description: "Patient race",
                        dataType: "string"
                    },
                    {
                        name: "ethnicity",
                        label: "Ethnicity",
                        description: "Patient ethnicity",
                        dataType: "string"
                    },
                    {
                        name: "encounter_period_years",
                        label: "Encounter Period (years)",
                        description: "Encounter period rounded to years",
                        dataType: "integer"
                    },
                    {
                        name: "encounter_period_months",
                        label: "Encounter Period (months)",
                        description: "Encounter period rounded to months",
                        dataType: "integer"
                    },
                    {
                        name: "encounter_period_weeks",
                        label: "Encounter Period (weeks)",
                        description: "Encounter period rounded to weeks",
                        dataType: "integer"
                    },
                    {
                        name: "encounter_period_days",
                        label: "Encounter Period (days)",
                        description: "Encounter period rounded to days",
                        dataType: "integer"
                    },
                    {
                        name: "condition",
                        label: "Condition",
                        description: "Condition",
                        dataType: "string"
                    },
                    {
                        name: "medication",
                        label: "Medication",
                        description: "Medication",
                        dataType: "string"
                    },
                    {
                        name: "procedure_",
                        label: "Procedure",
                        description: "Procedure",
                        dataType: "string"
                    },
                    {
                        name: "icd9_code",
                        label: "ICD9 Code",
                        description: "ICD9 Code",
                        dataType: "string"
                    },
                    {
                        name: "coding",
                        label: "Coding",
                        description: "Coding",
                        dataType: "string"
                    },
                    {
                        name: "queryid",
                        label: "Query ID",
                        description: "Query ID",
                        dataType: "string"
                    },
                    {
                        name: "cnt",
                        label: "Count",
                        description: "Aggregate count",
                        dataType: "integer"
                    }
                ],
                rows: [
                    [ null, "0-18", "M", null, "BLACK/CAPE VERDEAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 10 ],
                    [ null, "0-18", null, null, "ASIAN", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 10 ],
                    [ null, "0-18", null, null, null, null, null, null, null, null, null, null, "V292", null, "7fd1bd31", 10 ],
                    [ null, "0-18", "M", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 11 ],
                    [ null, "0-18", "F", null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 11 ],
                    [ null, "0-18", null, null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 11 ],
                    [ null, "0-18", "M", null, "MULTI RACE ETHNICITY", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 11 ],
                    [ null, "0-18", "F", null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 11 ],
                    [ null, "0-18", "F", null, "BLACK/CAPE VERDEAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 12 ],
                    [ null, "0-18", "M", null, "MULTI RACE ETHNICITY", null, null, null, null, null, null, null, null, null, "7fd1bd31", 12 ],
                    [ null, "0-18", "M", null, "OTHER", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 13 ],
                    [ null, "0-18", "F", null, "ASIAN - CHINESE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 14 ],
                    [ null, "0-18", "M", null, "AMERICAN INDIAN/ALASKA NATIVE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 14 ],
                    [ null, "0-18", "M", null, "AMERICAN INDIAN/ALASKA NATIVE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 14 ],
                    [ null, "0-18", "F", null, "OTHER", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 14 ],
                    [ null, "0-18", "M", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 14 ],
                    [ null, "0-18", "M", null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 15 ],
                    [ null, "0-18", "F", null, "ASIAN - CHINESE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 15 ],
                    [ null, "0-18", "M", null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 15 ],
                    [ null, "0-18", "M", null, "ASIAN - CHINESE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 15 ],
                    [ null, "0-18", "M", null, "ASIAN - CHINESE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 16 ],
                    [ null, "0-18", null, null, "BLACK/CAPE VERDEAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 17 ],
                    [ null, "0-18", null, null, "MULTI RACE ETHNICITY", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 18 ],
                    [ null, "0-18", "F", null, "WHITE", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 18 ],
                    [ null, "0-18", "M", null, "WHITE", null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 18 ],
                    [ null, "0-18", null, null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 18 ],
                    [ null, "0-18", "F", null, "ASIAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 19 ],
                    [ null, "0-18", null, null, "MULTI RACE ETHNICITY", null, null, null, null, null, null, null, null, null, "7fd1bd31", 20 ],
                    [ null, "0-18", null, null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 22 ],
                    [ null, "0-18", null, null, "AMERICAN INDIAN/ALASKA NATIVE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 22 ],
                    [ null, "0-18", null, null, "AMERICAN INDIAN/ALASKA NATIVE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 22 ],
                    [ null, "0-18", null, null, "BLACK/CAPE VERDEAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 22 ],
                    [ null, "0-18", "M", null, "WHITE", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 23 ],
                    [ null, "0-18", "F", null, "WHITE", null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 25 ],
                    [ null, "0-18", null, null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 26 ],
                    [ null, "0-18", null, null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 26 ],
                    [ null, "0-18", null, null, "OTHER", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 27 ],
                    [ null, "0-18", "F", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 27 ],
                    [ null, "0-18", "M", null, "ASIAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 27 ],
                    [ null, "0-18", "M", null, null, null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 27 ],
                    [ null, "0-18", "M", null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 28 ],
                    [ null, "0-18", null, null, "ASIAN - CHINESE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 29 ],
                    [ null, "0-18", "M", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 30 ],
                    [ null, "0-18", null, null, "ASIAN - CHINESE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 31 ],
                    [ null, "0-18", "M", null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 31 ],
                    [ null, "0-18", "F", null, null, null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 38 ],
                    [ null, "0-18", "F", null, null, null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 39 ],
                    [ null, "0-18", null, null, "WHITE", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 41 ],
                    [ null, "0-18", "F", null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 42 ],
                    [ null, "0-18", null, null, "WHITE", null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 43 ],
                    [ null, "0-18", "F", null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 43 ],
                    [ null, "0-18", "M", null, null, null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 45 ],
                    [ null, "0-18", null, null, "ASIAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 46 ],
                    [ null, "0-18", null, null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 57 ],
                    [ null, "0-18", null, null, null, null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 66 ],
                    [ null, "0-18", null, null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 70 ],
                    [ null, "0-18", null, null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 74 ],
                    [ null, "0-18", null, null, null, null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 83 ],
                    [ null, "0-18", "F", null, "WHITE", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 109 ],
                    [ null, "0-18", "F", null, "OTHER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 120 ],
                    [ null, "0-18", "F", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 120 ],
                    [ null, "0-18", "F", null, "OTHER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 124 ],
                    [ null, "0-18", "F", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, null, null, "7fd1bd31", 124 ],
                    [ null, "0-18", "M", null, "OTHER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 150 ],
                    [ null, "0-18", "M", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 152 ],
                    [ null, "0-18", "M", null, "OTHER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 153 ],
                    [ null, "0-18", "M", null, "WHITE", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 156 ],
                    [ null, "0-18", "M", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, null, null, "7fd1bd31", 159 ],
                    [ null, "0-18", "F", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 159 ],
                    [ null, "0-18", "F", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, null, null, "7fd1bd31", 162 ],
                    [ null, "0-18", "M", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 174 ],
                    [ null, "0-18", "M", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, null, null, "7fd1bd31", 177 ],
                    [ null, "0-18", "F", null, null, null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 193 ],
                    [ null, "0-18", "F", null, "ASIAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 246 ],
                    [ null, "0-18", "F", null, "ASIAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 257 ],
                    [ null, "0-18", "M", null, null, null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 259 ],
                    [ null, "0-18", null, null, "WHITE", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 265 ],
                    [ null, "0-18", null, null, "OTHER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 270 ],
                    [ null, "0-18", null, null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 272 ],
                    [ null, "0-18", null, null, "OTHER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 277 ],
                    [ null, "0-18", null, null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, null, null, "7fd1bd31", 283 ],
                    [ null, "0-18", "M", null, "ASIAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 299 ],
                    [ null, "0-18", "M", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 303 ],
                    [ null, "0-18", "M", null, "ASIAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 309 ],
                    [ null, "0-18", "F", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 310 ],
                    [ null, "0-18", "M", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 320 ],
                    [ null, "0-18", "F", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 321 ],
                    [ null, "0-18", null, null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 333 ],
                    [ null, "0-18", null, null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, null, null, "7fd1bd31", 339 ],
                    [ null, "0-18", null, null, null, null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 452 ],
                    [ null, "0-18", null, null, "ASIAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 545 ],
                    [ null, "0-18", null, null, "ASIAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 566 ],
                    [ null, "0-18", null, null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 613 ],
                    [ null, "0-18", null, null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 641 ],
                    [ null, "0-18", "F", null, "WHITE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 1500 ],
                    [ null, "0-18", "F", null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 1569 ],
                    [ null, "0-18", "M", null, "WHITE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 1749 ],
                    [ null, "0-18", "M", null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 1834 ],
                    [ null, "0-18", "F", null, null, null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 2564 ],
                    [ null, "0-18", "F", null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 2672 ],
                    [ null, "0-18", "M", null, null, null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 2941 ],
                    [ null, "0-18", "M", null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 3073 ],
                    [ null, "0-18", null, null, "WHITE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 3249 ],
                    [ null, "0-18", null, null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 3403 ],
                    [ null, "0-18", null, null, null, null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 5505 ],
                    [ null, "0-18", null, null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 5745 ],
                    [ null, "19-44", "F", null, "WHITE", null, null, null, null, null, null, null, "V270", null, "7fd1bd31", 17 ],
                    [ null, "19-44", null, null, "WHITE", null, null, null, null, null, null, null, "V270", null, "7fd1bd31", 17 ],
                    [ null, "19-44", "F", null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 28 ],
                    [ null, "19-44", null, null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 28 ],
                    [ null, "19-44", "F", null, null, null, null, null, null, null, null, null, "V270", null, "7fd1bd31", 35 ],
                    [ null, "19-44", null, null, null, null, null, null, null, null, null, null, "V270", null, "7fd1bd31", 35 ],
                    [ null, "19-44", "F", null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 49 ],
                    [ null, "19-44", null, null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 49 ],
                    [ null, "45-64", "F", null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 11 ],
                    [ null, "45-64", null, null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 14 ],
                    [ null, "45-64", null, null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 18 ],
                    [ null, null, "M", null, null, null, null, null, null, null, null, null, "V2652", null, "7fd1bd31", 10 ],
                    [ null, null, null, null, "ASIAN", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 10 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, "V292", null, "7fd1bd31", 10 ],
                    [ null, null, "F", null, "WHITE", null, null, null, null, null, null, null, "V2651", null, "7fd1bd31", 10 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, "V2652", null, "7fd1bd31", 10 ],
                    [ null, null, null, null, "WHITE", null, null, null, null, null, null, null, "V2651", null, "7fd1bd31", 10 ],
                    [ null, null, "M", null, "BLACK/CAPE VERDEAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 10 ],
                    [ null, null, "M", null, "MULTI RACE ETHNICITY", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 11 ],
                    [ null, null, "F", null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 11 ],
                    [ null, null, "M", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 11 ],
                    [ null, null, null, null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 11 ],
                    [ null, null, "F", null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 12 ],
                    [ null, null, "M", null, "MULTI RACE ETHNICITY", null, null, null, null, null, null, null, null, null, "7fd1bd31", 12 ],
                    [ null, null, "M", null, "OTHER", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 13 ],
                    [ null, null, "F", null, "OTHER", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 14 ],
                    [ null, null, "M", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 14 ],
                    [ null, null, "M", null, "AMERICAN INDIAN/ALASKA NATIVE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 14 ],
                    [ null, null, "F", null, "BLACK/CAPE VERDEAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 14 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, "V2651", null, "7fd1bd31", 14 ],
                    [ null, null, "M", null, "AMERICAN INDIAN/ALASKA NATIVE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 14 ],
                    [ null, null, "F", null, "ASIAN - CHINESE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 14 ],
                    [ null, null, "F", null, null, null, null, null, null, null, null, null, "V2651", null, "7fd1bd31", 14 ],
                    [ null, null, "M", null, "ASIAN - CHINESE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 15 ],
                    [ null, null, "M", null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 15 ],
                    [ null, null, "F", null, "ASIAN - CHINESE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 16 ],
                    [ null, null, "M", null, "ASIAN - CHINESE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 16 ],
                    [ null, null, "M", null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 16 ],
                    [ null, null, null, null, "BLACK/CAPE VERDEAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 17 ],
                    [ null, null, null, null, "MULTI RACE ETHNICITY", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 18 ],
                    [ null, null, "M", null, "WHITE", null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 18 ],
                    [ null, null, null, null, "WHITE", null, null, null, null, null, null, null, "V270", null, "7fd1bd31", 18 ],
                    [ null, null, "F", null, "WHITE", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 18 ],
                    [ null, null, "F", null, "WHITE", null, null, null, null, null, null, null, "V270", null, "7fd1bd31", 18 ],
                    [ null, null, null, null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 18 ],
                    [ null, null, "F", null, "ASIAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 19 ],
                    [ null, null, null, null, "MULTI RACE ETHNICITY", null, null, null, null, null, null, null, null, null, "7fd1bd31", 20 ],
                    [ null, null, null, null, "AMERICAN INDIAN/ALASKA NATIVE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 22 ],
                    [ null, null, null, null, "AMERICAN INDIAN/ALASKA NATIVE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 22 ],
                    [ null, null, null, null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 22 ],
                    [ null, null, "M", null, "WHITE", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 23 ],
                    [ null, null, null, null, "BLACK/CAPE VERDEAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 24 ],
                    [ null, null, "F", null, "WHITE", null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 25 ],
                    [ null, null, null, null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 26 ],
                    [ null, null, "M", null, "ASIAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 27 ],
                    [ null, null, "F", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 27 ],
                    [ null, null, null, null, "OTHER", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 27 ],
                    [ null, null, "M", null, null, null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 27 ],
                    [ null, null, null, null, "UNABLE TO OBTAIN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 28 ],
                    [ null, null, "M", null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 28 ],
                    [ null, null, null, null, "ASIAN - CHINESE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 29 ],
                    [ null, null, "M", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 30 ],
                    [ null, null, "M", null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 32 ],
                    [ null, null, null, null, "ASIAN - CHINESE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 32 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, "V270", null, "7fd1bd31", 37 ],
                    [ null, null, "F", null, null, null, null, null, null, null, null, null, "V270", null, "7fd1bd31", 37 ],
                    [ null, null, "F", null, null, null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 38 ],
                    [ null, null, "F", null, null, null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 39 ],
                    [ null, null, null, null, "WHITE", null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 41 ],
                    [ null, null, "F", null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 42 ],
                    [ null, null, null, null, "WHITE", null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 43 ],
                    [ null, null, "F", null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 45 ],
                    [ null, null, "M", null, null, null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 45 ],
                    [ null, null, null, null, "ASIAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 46 ],
                    [ null, null, null, null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 57 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, "V298", null, "7fd1bd31", 66 ],
                    [ null, null, null, null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 70 ],
                    [ null, null, null, null, "PATIENT DECLINED TO ANSWER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 77 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, "V202", null, "7fd1bd31", 83 ],
                    [ null, null, "F", null, "WHITE", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 109 ],
                    [ null, null, "F", null, "OTHER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 120 ],
                    [ null, null, "F", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 120 ],
                    [ null, null, "F", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, null, null, "7fd1bd31", 124 ],
                    [ null, null, "F", null, "OTHER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 126 ],
                    [ null, null, "M", null, "OTHER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 150 ],
                    [ null, null, "M", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 152 ],
                    [ null, null, "M", null, "OTHER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 154 ],
                    [ null, null, "M", null, "WHITE", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 156 ],
                    [ null, null, "F", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 159 ],
                    [ null, null, "M", null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, null, null, "7fd1bd31", 159 ],
                    [ null, null, "F", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, null, null, "7fd1bd31", 164 ],
                    [ null, null, "M", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 174 ],
                    [ null, null, "M", null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, null, null, "7fd1bd31", 178 ],
                    [ null, null, "F", null, null, null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 193 ],
                    [ null, null, "F", null, "ASIAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 246 ],
                    [ null, null, "M", null, null, null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 259 ],
                    [ null, null, "F", null, "ASIAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 263 ],
                    [ null, null, null, null, "WHITE", null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 265 ],
                    [ null, null, null, null, "OTHER", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 270 ],
                    [ null, null, null, null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 272 ],
                    [ null, null, null, null, "OTHER", null, null, null, null, null, null, null, null, null, "7fd1bd31", 280 ],
                    [ null, null, null, null, "HISPANIC OR LATINO", null, null, null, null, null, null, null, null, null, "7fd1bd31", 283 ],
                    [ null, null, "M", null, "ASIAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 299 ],
                    [ null, null, "M", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 303 ],
                    [ null, null, "M", null, "ASIAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 309 ],
                    [ null, null, "F", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 310 ],
                    [ null, null, "M", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 320 ],
                    [ null, null, "F", null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 327 ],
                    [ null, null, null, null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 333 ],
                    [ null, null, null, null, "UNKNOWN/NOT SPECIFIED", null, null, null, null, null, null, null, null, null, "7fd1bd31", 342 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, "V293", null, "7fd1bd31", 452 ],
                    [ null, null, null, null, "ASIAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 545 ],
                    [ null, null, null, null, "ASIAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 572 ],
                    [ null, null, null, null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 613 ],
                    [ null, null, null, null, "BLACK/AFRICAN AMERICAN", null, null, null, null, null, null, null, null, null, "7fd1bd31", 647 ],
                    [ null, null, "F", null, "WHITE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 1500 ],
                    [ null, null, "F", null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 1608 ],
                    [ null, null, "M", null, "WHITE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 1749 ],
                    [ null, null, "M", null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 1840 ],
                    [ null, null, "F", null, null, null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 2564 ],
                    [ null, null, "F", null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 2736 ],
                    [ null, null, "M", null, null, null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 2941 ],
                    [ null, null, "M", null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 3083 ],
                    [ null, null, null, null, "WHITE", null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 3249 ],
                    [ null, null, null, null, "WHITE", null, null, null, null, null, null, null, null, null, "7fd1bd31", 3448 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, "V290", null, "7fd1bd31", 5505 ],
                    [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, "7fd1bd31", 5819 ]
                ]
            }
        }
    ]);

    await models.View.bulkCreate([
        {
            id: 1,
            name: "Patients by Gender",
            description: "Shows the number of patients by gender",
            dataSourceId: 6,
            screenShot: "1.png",
            settings: {
                groupBy: "",
                column: "gender",
                filters: [],
                viewType: "donut3d"
            }
        },
        {
            id: 2,
            name: "Number of Patients by Age",
            description: "Shows the number of patients for each age in years that is found within the data",
            dataSourceId: 6,
            screenShot: "2.png",
            settings: {
                viewType: "column3d",
                column : "age",
                groupBy: "",
                filters: [
                    {
                        left: "age",
                        operator: "!==",
                        right: {
                            type: "null",
                            value: ""
                        }
                    }
                ],
            }
        },
        {
            id: 3,
            name: "Newborns Ethnicity by CDC Age Group",
            description: "Shows the ethnicity of newborns grouped by CDC age group",
            dataSourceId: 7,
            screenShot: "3.png",
            settings: {
                viewType: "column3d",
                column: "ethnicity",
                groupBy: "age_group",
                filters: []
            }
        },
        {
            id: 4,
            name: "0 to 18 Year Old Patient Gender by Age Group",
            description: "0 to 18 year old patients genders grouped by age groups",
            dataSourceId: 7,
            screenShot: "4.png",
            settings: {
                groupBy: "age_group",
                column: "gender",
                filters: [],
                viewType: "column"
            }
        }
    ]);
};
