services:

  # NginX Server for the dashboard frontend static content
  # This uses minimal NginX configuration from ./nginx.conf. 
  # TODO: Add config to cache static assets (images, css...)
  # TODO: Expose nginx logs?
  web:
    container_name: cumulus-dashboard-frontend
    build:
      context: ..
      dockerfile: ./docker/frontend.Dockerfile
    environment:
      - NODE_ENV=$NODE_ENV
    ports:
      - $PORT:80
    volumes:
      - ../dist/frontend:/usr/share/nginx/html 
    depends_on:
      - db

  api:
    container_name: cumulus-dashboard-backend
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - 4001:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=$DATABASE_URL
      - NODE_ENV=$NODE_ENV
      - MAILGUN_API_KEY=$MAILGUN_API_KEY
      - MAILGUN_DOMAIN=$MAILGUN_DOMAIN
      - THROTTLE=$THROTTLE
      - AGGREGATOR_URL=$AGGREGATOR_URL
      - AGGREGATOR_API_KEY=$AGGREGATOR_API_KEY
      - AGGREGATOR_ENABLED=$AGGREGATOR_ENABLED
      - NODE_DEBUG=$NODE_DEBUG
      - CUMULUS_ADMIN_EMAIL=$CUMULUS_ADMIN_EMAIL
      - REGIONAL_CLUSTER_EMAIL=$REGIONAL_CLUSTER_EMAIL
      - APP_EMAIL_FROM=$APP_EMAIL_FROM
      - REACT_APP_BACKEND_HOST=$REACT_APP_BACKEND_HOST
    volumes:
      - ../backend:/app/backend
      - ../dist/frontend:/app/dist/frontend

  db:
    container_name: cumulus-dashboard-db
    image: postgres:14
    restart: on-failure
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DATABASE
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGPORT=$DB_PORT
    volumes:
       - cumulus-dashboard-db-data:/var/lib/postgresql/data/pgdata
volumes:
   cumulus-dashboard-db-data:
