export interface Schema {
    templates: Template[]
    sections?: {
        [id: string]: {
            name: string
            description?: string
        }
    },
    parameters: {
        [parameter_id: string]: ParameterDescriptor
    }
}

export type ParameterDescriptor = (
    StringParameterDescriptor |
    NumberParameterDescriptor |
    BooleanParameterDescriptor |
    DateParameterDescriptor |
    EnumParameterDescriptor |
    CheckListParameterDescriptor
);

export interface BaseParameterDescriptor {
    name: string
    description?: string
}

export interface StringParameterDescriptor extends BaseParameterDescriptor, Omit<React.InputHTMLAttributes<HTMLInputElement>, "name"> {
    type: "string"
}

export interface DateParameterDescriptor extends BaseParameterDescriptor {
    type: "date"
}

export interface NumberParameterDescriptor extends BaseParameterDescriptor {
    type : "number"
    min ?: number
    max ?: number
    step?: number
}

export interface BooleanParameterDescriptor extends BaseParameterDescriptor {
    type: "boolean"
}

export interface EnumParameterDescriptor extends BaseParameterDescriptor {
    type: "enum"
    values: { value: string|number, label?: string, title?: string }[]
}

export interface CheckListParameterDescriptor extends BaseParameterDescriptor {
    type: "checklist"
    items: {
        value: any,
        label?: string
        description?: string
    }[]
}


export interface Template {
    id: string
    name: string
    variables?: {
        id      : string
        section?: string
        group  ?: string
        [key: string]: any
    }[]
}

export interface Node<Type=string> {
    label: string
    description?: string
    type: Type
    children?: Node[]
}

export interface Section extends Node<"section"> {
    parameters: {
        [parameter_id: string]: ParameterRuntimeArgs
    }
}

export interface ParameterRuntimeArgs {
    [key: string]: any
}

export interface Group<T> {
    label?: string
    description?: string
    items: T[]
}


export const schema: Schema = {
    templates: [
        {
            id: "template_1",
            name: "Adverse Drug Events (ADE)",
            variables: [
                {
                    id: "period_start",
                    section: "StudyPeriod",
                    defaultValue: "",
                    required: false
                },
                {
                    id: "period_end",
                    section: "StudyPeriod",
                    defaultValue: "",
                    required: false
                },
                {
                    id: "include_history",
                    section: "StudyPeriod",
                    defaultValue: false
                },
                {
                    id: "age_min",
                    section: "Demographics",
                    group: "AgeMin",
                },
                // {
                //     id: "patientAgeMinUnits",
                //     section: "Demographics",
                //     group: "AgeMin",
                // },
                {
                    id: "age_max",
                    section: "Demographics",
                    group: "AgeMax",
                },
                // {
                //     id: "patientAgeMaxUnits",
                //     section: "Demographics",
                //     group: "AgeMax",
                // },
                {
                    id: "gender_female",
                    section: "Demographics",
                    group: "clinicalSex",
                    defaultValue: false,
                    set: "FHIR Patient Gender"
                },
                {
                    id: "gender_male",
                    section: "Demographics",
                    group: "clinicalSex",
                    defaultValue: false,
                    set: "FHIR Patient Gender"
                },
                {
                    id: "gender_other",
                    section: "Demographics",
                    group: "clinicalSex",
                    defaultValue: false,
                    set: "FHIR Patient Gender"
                },
                {
                    id: "gender_unknown",
                    section: "Demographics",
                    group: "clinicalSex",
                    defaultValue: false,
                    set: "FHIR Patient Gender"
                },
                {
                    id: "enc_class_list",
                    section: "HealthcareSetting",
                    defaultValue: ""
                },
                {
                    id: "encounter_type",
                    section: "HealthcareSetting"
                },
                {
                    id: "note_type",
                    section: "HealthcareSetting",
                    list: "note-types",
                },
                {
                    id: "enc_min",
                    section: "HealthcareUtilization",
                    max: "$maxCountVisits",
                },
                {
                    id: "enc_max",
                    section: "HealthcareUtilization",
                    min: "$minCountVisits",
                },
                {
                    id: "enc_days_min",
                    section: "HealthcareUtilization",
                    min: 0,
                    step: 1
                },
                {
                    id: "dx_variables",
                    section: "StudyVariables",
                    defaultValue: [
                        { name: "skin", value: "2.16.840.1.113883.3.526.3.1010" },
                        { name: "melanoma", value: "2.16.840.1.113883.3.526.3.1010" },
                        { name: "melanoma_malignant", value: "2.16.840.1.113883.3.1434.1038" },
                        { name: "melanoma_malignant", value: "2.16.840.1.113883.3.464.1003.108.11.1018" },
                        { name: "sarcoma", value: "2.16.840.1.113883.3.526.3.1010" },
                        { name: "squamous", value: "2.16.840.1.113883.3.526.3.1010" },
                        { name: "condition", value: "2.16.840.1.113883.17.4077.3.2028" },
                        { name: "renal_disease", value: "2.16.840.1.113762.1.4.1029.335" },
                        { name: "esrd", value: "2.16.840.1.113762.1.4.1235.172" },
                        { name: "ckd", value: "2.16.840.1.113762.1.4.1078.114" },
                        { name: "dialysis", value: "2.16.840.1.113762.1.4.1078.342" },
                        { name: "nephrotic_syndrome", value: "2.16.840.1.113883.3.464.1003.109.12.1018" },
                        { name: "inflammatory", value: "2.16.840.1.113883.3.3157.1834" },
                        { name: "ibd", value: "2.16.840.1.113762.1.4.1078.879" },
                        { name: "crohns", value: "2.16.840.1.113762.1.4.1034.576" },
                        { name: "arthritis_ra", value: "2.16.840.1.113762.1.4.1222.651" },
                        { name: "arthritis_ra", value: "2.16.840.1.113762.1.4.1222.81" },
                        { name: "lupus", value: "2.16.840.1.113883.3.464.1003.117.12.1010" },
                        { name: "any", value: "2.16.840.1.113883.3.666.5.1940" },
                        { name: "any", value: "2.16.840.1.113762.1.4.1235.212" },
                        { name: "bacterial", value: "2.16.840.1.113762.1.4.1200.288" },
                        { name: "pna", value: "2.16.840.1.113762.1.4.1078.738" },
                        { name: "cmv", value: "2.16.840.1.113762.1.4.1146.2234" },
                        { name: "cmv", value: "2.16.840.1.113762.1.4.1146.2233" },
                        { name: "rsv", value: "2.16.840.1.113762.1.4.1078.754" },
                        { name: "influenza", value: "2.16.840.1.113762.1.4.1078.747" },
                        { name: "shingles", value: "2.16.840.1.113762.1.4.1222.1478" },
                        { name: "hepatitis_b", value: "2.16.840.1.113883.3.464.1003.110.12.1025" },
                        { name: "hepatitis_c", value: "2.16.840.1.113762.1.4.1222.30" },
                        { name: "cardiomyopathy", value: "2.16.840.1.113762.1.4.1222.579" },
                        { name: "attack", value: "2.16.840.1.113883.3.666.5.3011" },
                        { name: "failure", value: "2.16.840.1.113762.1.4.1222.1543" },
                        { name: "cohort", value: "2.16.840.1.113762.1.4.1182.308" },
                        { name: "essential", value: "2.16.840.1.113883.3.464.1003.104.12.1011" },
                        { name: "any", value: "2.16.840.1.113762.1.4.1251.12" },
                        { name: "hypertensive_ckd", value: "2.16.840.1.113883.3.464.1003.109.12.1017" },
                        { name: "disorder", value: "2.16.840.1.113762.1.4.1219.35" },
                        { name: "preexisting", value: "2.16.840.1.113883.3.464.1003.198.12.1075" },
                        { name: "complications", value: "2.16.840.1.113762.1.4.1222.1537" },
                        { name: "t2d_related_dx", value: "2.16.840.1.113762.1.4.1078.440" },
                        { name: "diabetic_nephropathy", value: "2.16.840.1.113883.3.464.1003.109.12.1004" },
                        { name: "diabetic_ckd", value: "2.16.840.1.113762.1.4.1078.124" },
                    ]
                },
                {
                    id: "rx_variables",
                    section: "StudyVariables",
                    defaultValue: [
                        { name: "everolimus", value: "2.16.840.1.113762.1.4.1260.499" },
                        { name: "drugs", value: "2.16.840.1.113762.1.4.1219.192" },
                        { name: "systemic_therapy", value: "2.16.840.1.113883.3.666.5.803" },
                        { name: "immune_modulators", value: "2.16.840.1.113762.1.4.1248.124" },
                        { name: "coricosteroids_systemic", value: "2.16.840.1.113883.3.3616.200.110.102.2061" },
                        { name: "chemo_advanced", value: "2.16.840.1.113883.3.7643.2.1046" },
                        { name: "checkpoint", value: "2.16.840.1.113762.1.4.1133.6" },
                        { name: "keytruda", value: "2.16.840.1.113762.1.4.1260.496" },
                        { name: "ade_neutropenia", value: "2.16.840.1.113883.3.526.3.1538" },
                        { name: "any", value: "2.16.840.1.113762.1.4.1078.849" },
                        { name: "systemic", value: "2.16.840.1.113762.1.4.1133.6" },
                        { name: "therapies", value: "2.16.840.1.113762.1.4.1235.212" },
                        { name: "drugs", value: "2.16.840.1.113762.1.4.1190.58" },
                        { name: "drugs", value: "2.16.840.1.113883.3.600.1476" },
                        { name: "loop", value: "2.16.840.1.113762.1.4.1078.898" },
                        { name: "potassium", value: "2.16.840.1.113762.1.4.1213.41" },
                        { name: "thiazide", value: "2.16.840.1.113762.1.4.1078.8" },
                    ]
                },
                {
                    id: "lab_variables",
                    section: "StudyVariables",
                    defaultValue: [
                        { name: "with_diff", value: "1.3.6.1.4.1.6997.4.1.2.271.13.38167.1.1.999.594" },
                        { name: "comprehensive", value: "2.16.840.1.113762.1.4.1078.867" },
                        { name: "egfr", value: "2.16.840.1.113762.1.4.1078.397" },
                        { name: "function", value: "2.16.840.1.113762.1.4.1078.867" },
                        { name: "ggt", value: "2.16.840.1.113762.1.4.1222.806" },
                        { name: "pt", value: "2.16.840.1.113883.3.3616.200.110.102.5037" },
                        { name: "inr", value: "2.16.840.1.113883.3.117.1.7.1.213" },
                        { name: "serum_cr", value: "2.16.840.1.113762.1.4.1146.2206" },
                        { name: "urine_cr", value: "2.16.840.1.113762.1.4.1178.87" },
                        { name: "urine_alb_cr_ratio", value: "2.16.840.1.113883.3.6929.3.1007" },
                        { name: "urine_protein_cr_ratio", value: "2.16.840.1.113762.1.4.1222.790" },
                        { name: "blood_cr", value: "2.16.840.1.113762.1.4.1222.111" },
                        { name: "serum_rf", value: "2.16.840.1.113762.1.4.1222.812" },
                        { name: "blood_esr", value: "2.16.840.1.113762.1.4.1222.1609" },
                        { name: "crp", value: "2.16.840.1.113762.1.4.1146.1933" },
                        { name: "tsh", value: "2.16.840.1.113762.1.4.1146.2156" },
                        { name: "t3", value: "2.16.840.1.113762.1.4.1078.864" },
                        { name: "t4", value: "2.16.840.1.113762.1.4.1078.865" },
                        { name: "screening", value: "2.16.840.1.113762.1.4.1221.122" },
                        { name: "glucose_test", value: "2.16.840.1.113762.1.4.1045.134" },
                    ]
                },
                // {
                //     id: "doc_variables",
                //     section: "StudyVariables",
                //     defaultValue: [
                //         { name: "kidney", value: "2.16.840.1.113762.1.4.1222.864" },
                //         { name: "skin", value: "2.16.840.1.113762.1.4.1222.867" },
                //         { name: "lung", value: "2.16.840.1.113883.3.1434.1011" },
                //         { name: "bone", value: "2.16.840.1.113762.1.4.1222.870" },
                //         { name: "muscle", value: "2.16.840.1.113762.1.4.1222.868" },
                //     ]
                // },
                {
                    id: "proc_variables",
                    section: "StudyVariables",
                    defaultValue: [
                        { name: "services"   , value: "2.16.840.1.113883.3.464.1003.109.12.1013" },
                        { name: "other_major", value: "2.16.840.1.113883.3.464.1003.198.12.1075" }
                    ]
                }
            ]
        }
    ],
    sections: {
        StudyPeriod: {
            name: "Study period",
            description: "The study period defines the first and last date of patient encounters. All studies retrospective observational studies using FHIR data from the electronic health record system."
        },
        Demographics: {
            name: "Demographics"
        },
        HealthcareSetting: {
            name: "Healthcare Setting"
        },
        HealthcareUtilization: {
            name: "Healthcare Utilization"
        },
        StudyVariables: {
            name: "STUDY VARIABLES"
        }
    },
    parameters: {
        period_start: {
            name: "Start Date",
            description: "[FHIR Encounter Period](https://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-encounter-definitions.html#Encounter.period) start date",
            type: "date"
        },
        period_end: {
            name: "End Date",
            description: "[FHIR Encounter Period](https://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-encounter-definitions.html#Encounter.period) end date",
            type: "date"
        },
        include_history: {
            name: "Include patient history",
            description: "If true, select patient historical data before the study period for patients who match all other inclusion criteria.",
            type: "boolean"
        },
        age_min: {
            name: "Min Patient Age",
            description: "Minimum FHIR Patient age at the time of visit",
            type: "number",
            min : 0,
            max : 130,
            step: 1
        },
        patientAgeMinUnits: {
            name: "Min Age Units",
            type: "enum",
            values: [
                { value: "years" },
                { value: "months" },
                { value: "weeks" }
            ]
        },
        age_max: {
            name: "Max Patient Age",
            description: "Maximum FHIR Patient age at the time of visit",
            type: "number",
            min: 0,
            max: 130,
            step: 1
        },
        patientAgeMaxUnits: {
            name: "Max Age Units",
            type: "enum",
            values: [
                { value: "years" },
                { value: "months" },
                { value: "weeks" }
            ]
        },
        gender_female: {
            name: "Female",
            type: "boolean",
        },
        gender_male: {
            name: "Male",
            type: "boolean",
        },
        gender_other: {
            name: "Other",
            type: "boolean",
        },
        gender_unknown: {
            name: "Unknown",
            type: "boolean",
        },
        enc_class_list: {
            name: "FHIR Encounter.class",
            type: "enum",
            values: [
                { value: ""      , label: "not specified (include all)" },
                { value: "AMB"   , label: "Ambulatory" },
                { value: "EMER"  , label: "Emergency" },
                { value: "FLD"   , label: "Field" },
                { value: "HH"    , label: "Home health" },
                { value: "IMP"   , label: "Inpatient encounter" },
                { value: "ACUTE" , label: "Inpatient acute" },
                { value: "NONAC" , label: "Inpatient non-acute" },
                { value: "OBSENC", label: "Observation encounter" },
                { value: "PRENC" , label: "Pre-admission" },
                { value: "SS"    , label: "Short stay" },
                { value: "VR"    , label: "Virtual" },
            ],
            description: "Select what class of encounters should be used in your study. [ValueSet](https://terminology.hl7.org/1.0.0/ValueSet-v3-ActEncounterCode.html) 🔗"
        },
        encounter_type: {
            name: "FHIR Encounter.serviceType",
            type: "enum",
            values: [
                { value: "", label: "Not specified (include all)" },
                ...[
                      { value: "1",   label: "Adoption/Permanent Care Info/Support" },
                      { value: "2",   label: "Aged Care Assessment" },
                      { value: "3",   label: "Aged Care Information/Referral" },
                      { value: "4",   label: "Aged Residential Care" },
                      { value: "5",   label: "Case Management for Older Persons" },
                      { value: "6",   label: "Delivered Meals (Meals On Wheels)" },
                      { value: "7",   label: "Friendly Visiting" },
                      { value: "8",   label: "Home Care/Housekeeping Assistance" },
                      { value: "9",   label: "Home Maintenance and Repair" },
                      { value: "10",  label: "Personal Alarms/Alerts" },
                      { value: "11",  label: "Personal Care for Older Persons" },
                      { value: "12",  label: "Planned Activity Groups" },
                      { value: "13",  label: "Acupuncture" },
                      { value: "14",  label: "Alexander Technique Therapy" },
                      { value: "15",  label: "Aromatherapy" },
                      { value: "16",  label: "Biorhythm Services" },
                      { value: "17",  label: "Bowen Therapy" },
                      { value: "18",  label: "Chinese Herbal Medicine" },
                      { value: "19",  label: "Feldenkrais" },
                      { value: "20",  label: "Homoeopathy" },
                      { value: "21",  label: "Hydrotherapy" },
                      { value: "22",  label: "Hypnotherapy" },
                      { value: "23",  label: "Kinesiology" },
                      { value: "24",  label: "Magnetic Therapy" },
                      { value: "25",  label: "Massage Therapy" },
                      { value: "26",  label: "Meditation" },
                      { value: "27",  label: "Myotherapy" },
                      { value: "28",  label: "Naturopathy" },
                      { value: "29",  label: "Reflexology" },
                      { value: "30",  label: "Reiki" },
                      { value: "31",  label: "Relaxation Therapy" },
                      { value: "32",  label: "Shiatsu" },
                      { value: "33",  label: "Western Herbal Medicine" },
                      { value: "34",  label: "Family Day care" },
                      { value: "35",  label: "Holiday Programs" },
                      { value: "36",  label: "Kindergarten Inclusion Support " },
                      { value: "37",  label: "Kindergarten/Preschool" },
                      { value: "38",  label: "Long Day Child Care" },
                      { value: "39",  label: "Occasional Child Care" },
                      { value: "40",  label: "Outside School Hours Care" },
                      { value: "41",  label: "Children's Play Programs" },
                      { value: "42",  label: "Parenting/Family Support/Education" },
                      { value: "43",  label: "Playgroup" },
                      { value: "44",  label: "School Nursing" },
                      { value: "45",  label: "Toy Library" },
                      { value: "46",  label: "Child Protection/Child Abuse Report" },
                      { value: "47",  label: "Foster Care" },
                      { value: "48",  label: "Residential/Out-of-Home Care" },
                      { value: "49",  label: "Support - Young People Leaving Care" },
                      { value: "50",  label: "Audiology" },
                      { value: "51",  label: "Blood Donation" },
                      { value: "52",  label: "Chiropractic" },
                      { value: "53",  label: "Dietetics" },
                      { value: "54",  label: "Family Planning" },
                      { value: "55",  label: "Health Advocacy/Liaison Service" },
                      { value: "56",  label: "Health Information/Referral" },
                      { value: "57",  label: "Immunization" },
                      { value: "58",  label: "Maternal & Child Health" },
                      { value: "59",  label: "Nursing" },
                      { value: "60",  label: "Nutrition" },
                      { value: "61",  label: "Occupational Therapy" },
                      { value: "62",  label: "Optometry" },
                      { value: "63",  label: "Osteopathy" },
                      { value: "64",  label: "Pharmacy" },
                      { value: "65",  label: "Physiotherapy" },
                      { value: "66",  label: "Podiatry" },
                      { value: "67",  label: "Sexual Health" },
                      { value: "68",  label: "Speech Pathology/Therapy" },
                      { value: "69",  label: "Bereavement Counselling" },
                      { value: "70",  label: "Crisis Counselling" },
                      { value: "71",  label: "Family Counselling/Therapy" },
                      { value: "72",  label: "Family Violence Counselling" },
                      { value: "73",  label: "Financial Counselling" },
                      { value: "74",  label: "Generalist Counselling" },
                      { value: "75",  label: "Genetic Counselling" },
                      { value: "76",  label: "Health Counselling" },
                      { value: "77",  label: "Mediation" },
                      { value: "78",  label: "Problem Gambling Counselling" },
                      { value: "79",  label: "Relationship Counselling" },
                      { value: "80",  label: "Sexual Assault Counselling" },
                      { value: "81",  label: "Trauma Counselling" },
                      { value: "82",  label: "Victims of Crime Counselling" },
                      { value: "83",  label: "Cemetery Operation" },
                      { value: "84",  label: "Cremation" },
                      { value: "85",  label: "Death Service Information" },
                      { value: "86",  label: "Funeral Services" },
                      { value: "87",  label: "Endodontic" },
                      { value: "88",  label: "General Dental" },
                      { value: "89",  label: "Oral Medicine" },
                      { value: "90",  label: "Oral Surgery" },
                      { value: "91",  label: "Orthodontic" },
                      { value: "92",  label: "Paediatric Dentistry" },
                      { value: "93",  label: "Periodontic" },
                      { value: "94",  label: "Prosthodontic" },
                      { value: "95",  label: "Acquired Brain Injury Info/Referral" },
                      { value: "96",  label: "Disability Advocacy" },
                      { value: "97",  label: "Disability Aids & Equipment" },
                      { value: "98",  label: "Disability Case Management" },
                      { value: "99",  label: "Disability Day Programs/Activities" },
                      { value: "100", label: "Disability Information/Referral" },
                      { value: "101", label: "Disability Support Packages" },
                      { value: "102", label: "Disability Supported Accommodation" },
                      { value: "103", label: "Early Childhood Intervention" },
                      { value: "104", label: "Hearing Aids & Equipment" },
                      { value: "105", label: "Drug and/or Alcohol Counselling" },
                      { value: "106", label: "Drug/Alcohol Information/Referral" },
                      { value: "107", label: "Needle & Syringe Exchange" },
                      { value: "108", label: "Non-resid. Alcohol/Drug Treatment " },
                      { value: "109", label: "Pharmacotherapy" },
                      { value: "110", label: "Quit Program" },
                      { value: "111", label: "Residential Alcohol/Drug Treatment " },
                      { value: "112", label: "Adult/Community Education" },
                      { value: "113", label: "Higher Education" },
                      { value: "114", label: "Primary Education" },
                      { value: "115", label: "Secondary Education" },
                      { value: "116", label: "Training & Vocational Education" },
                      { value: "117", label: "Emergency Medical" },
                      { value: "118", label: "Employment Placement and/or Support" },
                      { value: "119", label: "Vocational Rehabilitation" },
                      { value: "120", label: "Work Safety/Accident Prevention" },
                      { value: "121", label: "Financial Assistance" },
                      { value: "122", label: "Financial Information/Advice" },
                      { value: "123", label: "Material Aid" },
                      { value: "124", label: "General Practice" },
                      { value: "125", label: "Accommodation Placement/Support" },
                      { value: "126", label: "Crisis/Emergency Accommodation" },
                      { value: "127", label: "Homelessness Support" },
                      { value: "128", label: "Housing Information/Referral" },
                      { value: "129", label: "Public Rental Housing" },
                      { value: "130", label: "Interpreting/Multilingual Service" },
                      { value: "131", label: "Juvenile Justice" },
                      { value: "132", label: "Legal Advocacy" },
                      { value: "133", label: "Legal Information/Advice/Referral" },
                      { value: "134", label: "Mental Health Advocacy" },
                      { value: "135", label: "Mental Health Assess/Triage/Crisis Response" },
                      { value: "136", label: "Mental Health Case Management" },
                      { value: "137", label: "Mental Health Information/Referral" },
                      { value: "138", label: "Mental Health Inpatient Services" },
                      { value: "139", label: "Mental Health Non-residential Rehab" },
                      { value: "140", label: "Mental Health Residential Rehab/CCU" },
                      { value: "141", label: "Psychiatry (Requires Referral)" },
                      { value: "142", label: "Psychology" },
                      { value: "143", label: "Martial Arts" },
                      { value: "144", label: "Personal Fitness Training" },
                      { value: "145", label: "Physical Activity Group" },
                      { value: "146", label: "Physical Activity Programs" },
                      { value: "147", label: "Physical Fitness Testing" },
                      { value: "148", label: "Pilates" },
                      { value: "149", label: "Self-Defence" },
                      { value: "150", label: "Sporting Club" },
                      { value: "151", label: "Yoga" },
                      { value: "152", label: "Food Safety" },
                      { value: "153", label: "Health Regulatory /Inspection /Cert." },
                      { value: "154", label: "Work Health/Safety Inspection/Cert." },
                      { value: "155", label: "Carer Support" },
                      { value: "156", label: "Respite Care" },
                      { value: "157", label: "Anatomical Pathology " },
                      { value: "158", label: "Pathology - Clinical Chemistry" },
                      { value: "159", label: "Pathology - General" },
                      { value: "160", label: "Pathology - Genetics" },
                      { value: "161", label: "Pathology - Haematology" },
                      { value: "162", label: "Pathology - Immunology" },
                      { value: "163", label: "Pathology - Microbiology" },
                      { value: "164", label: "Anaesthesiology - Pain Medicine" },
                      { value: "165", label: "Cardiology" },
                      { value: "166", label: "Clinical Genetics" },
                      { value: "167", label: "Clinical Pharmacology" },
                      { value: "168", label: "Dermatology" },
                      { value: "169", label: "Endocrinology" },
                      { value: "170", label: "Gastroenterology & Hepatology" },
                      { value: "171", label: "Geriatric Medicine" },
                      { value: "172", label: "Immunology & Allergy" },
                      { value: "173", label: "Infectious Diseases" },
                      { value: "174", label: "Intensive Care Medicine" },
                      { value: "175", label: "Medical Oncology" },
                      { value: "176", label: "Nephrology" },
                      { value: "177", label: "Neurology" },
                      { value: "178", label: "Occupational Medicine" },
                      { value: "179", label: "Palliative Medicine" },
                      { value: "180", label: "Public Health Medicine" },
                      { value: "181", label: "Rehabilitation Medicine" },
                      { value: "182", label: "Rheumatology" },
                      { value: "183", label: "Sleep Medicine" },
                      { value: "184", label: "Thoracic Medicine" },
                      { value: "185", label: "Gynaecological Oncology" },
                      { value: "186", label: "Obstetrics & Gynaecology" },
                      { value: "187", label: "Reproductive Endocrinology/Infertility" },
                      { value: "188", label: "Urogynaecology" },
                      { value: "189", label: "Neonatology & Perinatology" },
                      { value: "190", label: "Paediatric Cardiology" },
                      { value: "191", label: "Paediatric Clinical Genetics" },
                      { value: "192", label: "Paediatric Clinical Pharmacology" },
                      { value: "193", label: "Paediatric Endocrinology" },
                      { value: "194", label: "Paed. Gastroenterology/Hepatology" },
                      { value: "195", label: "Paediatric Haematology" },
                      { value: "196", label: "Paediatric Immunology & Allergy" },
                      { value: "197", label: "Paediatric Infectious Diseases" },
                      { value: "198", label: "Paediatric Intensive Care Medicine" },
                      { value: "199", label: "Paediatric Medical Oncology" },
                      { value: "200", label: "Paediatric Medicine" },
                      { value: "201", label: "Paediatric Nephrology" },
                      { value: "202", label: "Paediatric Neurology" },
                      { value: "203", label: "Paediatric Nuclear Medicine" },
                      { value: "204", label: "Paediatric Rehabilitation Medicine" },
                      { value: "205", label: "Paediatric Rheumatology" },
                      { value: "206", label: "Paediatric Sleep Medicine" },
                      { value: "207", label: "Paediatric Surgery" },
                      { value: "208", label: "Paediatric Thoracic Medicine" },
                      { value: "209", label: "Diag. Radiology /Xray /CT /Fluoroscopy" },
                      { value: "210", label: "Diagnostic Ultrasound" },
                      { value: "211", label: "Magnetic Resonance Imaging (MRI)" },
                      { value: "212", label: "Nuclear Medicine" },
                      { value: "213", label: "Obstetric/Gynaecological Ultrasound" },
                      { value: "214", label: "Radiation Oncology" },
                      { value: "215", label: "Cardiothoracic Surgery" },
                      { value: "216", label: "Neurosurgery" },
                      { value: "217", label: "Ophthalmology" },
                      { value: "218", label: "Orthopaedic Surgery" },
                      { value: "219", label: "Otolaryngology/Head & Neck Surgery" },
                      { value: "220", label: "Plastic & Reconstructive Surgery" },
                      { value: "221", label: "Surgery - General" },
                      { value: "222", label: "Urology" },
                      { value: "223", label: "Vascular Surgery" },
                      { value: "224", label: "Support Groups" },
                      { value: "225", label: "Air ambulance" },
                      { value: "226", label: "Ambulance" },
                      { value: "227", label: "Blood Transport" },
                      { value: "228", label: "Community Bus" },
                      { value: "229", label: "Flying Doctor Service" },
                      { value: "230", label: "Patient Transport" },
                      { value: "231", label: "A&E" },
                      { value: "232", label: "A&EP" },
                      { value: "233", label: "Abuse" },
                      { value: "234", label: "ACAS" },
                      { value: "235", label: "Access" },
                      { value: "236", label: "Accident" },
                      { value: "237", label: "Acute Inpatient Serv" },
                      { value: "238", label: "Adult Day Programs" },
                      { value: "239", label: "Adult Mental Health Services" },
                      { value: "240", label: "Advice" },
                      { value: "241", label: "Advocacy" },
                      { value: "242", label: "Aged Persons Mental " },
                      { value: "243", label: "Aged Persons Mental " },
                      { value: "244", label: "Aged Persons Mental " },
                      { value: "245", label: "Aids" },
                      { value: "246", label: "Al-Anon" },
                      { value: "247", label: "Alcohol" },
                      { value: "248", label: "Al-Teen" },
                      { value: "249", label: "Antenatal" },
                      { value: "250", label: "Anxiety" },
                      { value: "251", label: "Arthritis" },
                      { value: "252", label: "Assessment" },
                      { value: "253", label: "Assistance" },
                      { value: "254", label: "Asthma" },
                      { value: "255", label: "ATSS" },
                      { value: "256", label: "Attendant Care" },
                      { value: "257", label: "Babies" },
                      { value: "258", label: "Bathroom Modificatio" },
                      { value: "259", label: "Behavior" },
                      { value: "260", label: "Behavior Interventi" },
                      { value: "261", label: "Bereavement" },
                      { value: "262", label: "Bipolar" },
                      { value: "263", label: "Birth" },
                      { value: "264", label: "Birth Control" },
                      { value: "265", label: "Birthing Options" },
                      { value: "266", label: "BIST" },
                      { value: "267", label: "Blood" },
                      { value: "268", label: "Bone" },
                      { value: "269", label: "Bowel" },
                      { value: "270", label: "Brain" },
                      { value: "271", label: "Breast Feeding" },
                      { value: "272", label: "Breast Screen" },
                      { value: "273", label: "Brokerage" },
                      { value: "274", label: "Cancer" },
                      { value: "275", label: "Cancer Support" },
                      { value: "276", label: "Cardiovascular Disea" },
                      { value: "277", label: "Care Packages" },
                      { value: "278", label: "Carer" },
                      { value: "279", label: "Case Management" },
                      { value: "280", label: "Casualty" },
                      { value: "281", label: "Centrelink" },
                      { value: "282", label: "Chemists" },
                      { value: "283", label: "Child And Adolescent" },
                      { value: "284", label: "Child Care" },
                      { value: "285", label: "Child Services" },
                      { value: "286", label: "Children" },
                      { value: "287", label: "Children's Services" },
                      { value: "288", label: "Cholesterol" },
                      { value: "289", label: "Clothing" },
                      { value: "290", label: "Community Based Acco" },
                      { value: "291", label: "Community Care Unit" },
                      { value: "292", label: "Community Child And " },
                      { value: "293", label: "Community Health" },
                      { value: "294", label: "Community Residentia" },
                      { value: "295", label: "Community Transport" },
                      { value: "296", label: "Companion Visiting" },
                      { value: "297", label: "Companionship" },
                      { value: "298", label: "Consumer Advice" },
                      { value: "299", label: "Consumer Issues" },
                      { value: "300", label: "Continuing Care Serv" },
                      { value: "301", label: "Contraception Inform" },
                      { value: "302", label: "Coordinating Bodies" },
                      { value: "303", label: "Correctional Service" },
                      { value: "304", label: "Council Environmenta" },
                      { value: "305", label: "Counselling" },
                      { value: "306", label: "Criminal" },
                      { value: "307", label: "Crises" },
                      { value: "308", label: "Crisis Assessment An" },
                      { value: "309", label: "Crisis Assistance" },
                      { value: "310", label: "Crisis Refuge" },
                      { value: "311", label: "Day Program" },
                      { value: "312", label: "Deaf" },
                      { value: "313", label: "Dental Hygiene" },
                      { value: "314", label: "Dentistry" },
                      { value: "315", label: "Dentures" },
                      { value: "316", label: "Depression" },
                      { value: "317", label: "Detoxification" },
                      { value: "318", label: "Diabetes" },
                      { value: "319", label: "Diaphragm Fitting" },
                      { value: "320", label: "Dieticians" },
                      { value: "321", label: "Disabled Parking" },
                      { value: "322", label: "District Nursing" },
                      { value: "323", label: "Divorce" },
                      { value: "324", label: "Doctors" },
                      { value: "325", label: "Drink-Drive" },
                      { value: "326", label: "Dual Diagnosis Servi" },
                      { value: "327", label: "Early Choice" },
                      { value: "328", label: "Eating Disorder" },
                      { value: "330", label: "Emergency Relief" },
                      { value: "331", label: "Employment And Train" },
                      { value: "332", label: "Environment" },
                      { value: "333", label: "Equipment" },
                      { value: "334", label: "Exercise" },
                      { value: "335", label: "Facility" },
                      { value: "336", label: "Family Choice" },
                      { value: "337", label: "Family Law" },
                      { value: "338", label: "Family Options" },
                      { value: "339", label: "Family Services" },
                      { value: "340", label: "FFYA" },
                      { value: "341", label: "Financial Aid" },
                      { value: "342", label: "Fitness" },
                      { value: "343", label: "Flexible Care Packag" },
                      { value: "344", label: "Food" },
                      { value: "345", label: "Food Vouchers" },
                      { value: "346", label: "Forensic Mental Heal" },
                      { value: "347", label: "Futures" },
                      { value: "348", label: "Futures For Young Ad" },
                      { value: "349", label: "General Practitioner" },
                      { value: "350", label: "Grants" },
                      { value: "351", label: "Grief" },
                      { value: "352", label: "Grief Counselling" },
                      { value: "353", label: "HACC" },
                      { value: "354", label: "Heart Disease" },
                      { value: "355", label: "Help" },
                      { value: "356", label: "High Blood Pressure" },
                      { value: "357", label: "Home Help" },
                      { value: "358", label: "Home Nursing" },
                      { value: "359", label: "Homefirst" },
                      { value: "360", label: "Hospice Care" },
                      { value: "361", label: "Hospital Services" },
                      { value: "362", label: "Hospital To Home" },
                      { value: "364", label: "Hostel" },
                      { value: "365", label: "Hostel Accommodation" },
                      { value: "366", label: "Household Items" },
                      { value: "367", label: "Hypertension" },
                      { value: "368", label: "Illness" },
                      { value: "369", label: "Independent Living" },
                      { value: "370", label: "Information" },
                      { value: "371", label: "Injury" },
                      { value: "372", label: "Intake" },
                      { value: "373", label: "Intensive Mobile You" },
                      { value: "374", label: "Intervention" },
                      { value: "375", label: "Job Searching" },
                      { value: "376", label: "Justice" },
                      { value: "377", label: "Leisure" },
                      { value: "378", label: "Loans" },
                      { value: "379", label: "Low Income Earners" },
                      { value: "380", label: "Lung" },
                      { value: "381", label: "Making A Difference" },
                      { value: "382", label: "Medical Services" },
                      { value: "383", label: "Medical Specialists" },
                      { value: "384", label: "Medication Administr" },
                      { value: "385", label: "Menstrual Informatio" },
                      { value: "386", label: "Methadone" },
                      { value: "387", label: "Mobile Support And T" },
                      { value: "388", label: "Motor Neurone" },
                      { value: "389", label: "Multiple Sclerosis" },
                      { value: "390", label: "Neighbourhood House" },
                      { value: "391", label: "Nursing Home" },
                      { value: "392", label: "Nursing Mothers" },
                      { value: "393", label: "Obesity" },
                      { value: "394", label: "Occupational Health " },
                      { value: "395", label: "Optometrist" },
                      { value: "396", label: "Oral Hygiene" },
                      { value: "397", label: "Outpatients" },
                      { value: "398", label: "Outreach Service" },
                      { value: "399", label: "PADP" },
                      { value: "400", label: "Pain" },
                      { value: "401", label: "Pap Smear" },
                      { value: "402", label: "Parenting" },
                      { value: "403", label: "Peak Organizations" },
                      { value: "404", label: "Personal Care" },
                      { value: "405", label: "Pharmacies" },
                      { value: "406", label: "Phobias" },
                      { value: "407", label: "Physical" },
                      { value: "408", label: "Physical Activity" },
                      { value: "409", label: "Postnatal" },
                      { value: "410", label: "Pregnancy" },
                      { value: "411", label: "Pregnancy Tests" },
                      { value: "412", label: "Preschool" },
                      { value: "413", label: "Prescriptions" },
                      { value: "414", label: "Primary Mental Healt" },
                      { value: "415", label: "Property Maintenance" },
                      { value: "416", label: "Prostate" },
                      { value: "417", label: "Psychiatric" },
                      { value: "418", label: "Psychiatric Disabili" },
                      { value: "419", label: "Psychiatric Disabili" },
                      { value: "420", label: "Psychiatric Disabili" },
                      { value: "421", label: "Psychiatric Disabili" },
                      { value: "422", label: "Psychiatric Disabili" },
                      { value: "423", label: "Psychiatric Support" },
                      { value: "424", label: "Recreation" },
                      { value: "425", label: "Referral" },
                      { value: "426", label: "Refuge" },
                      { value: "427", label: "Rent Assistance" },
                      { value: "428", label: "Residential Faciliti" },
                      { value: "429", label: "Residential Respite" },
                      { value: "430", label: "Respiratory" },
                      { value: "431", label: "Response" },
                      { value: "432", label: "Rooming Houses" },
                      { value: "433", label: "Safe Sex" },
                      { value: "434", label: "Secure Extended Care" },
                      { value: "435", label: "Self Help" },
                      { value: "436", label: "Separation" },
                      { value: "437", label: "Services" },
                      { value: "438", label: "Sex Education" },
                      { value: "439", label: "Sexual Abuse" },
                      { value: "440", label: "Sexual Issues" },
                      { value: "441", label: "Sexually Transmitted" },
                      { value: "442", label: "SIDS" },
                      { value: "443", label: "Social Support" },
                      { value: "444", label: "Socialisation" },
                      { value: "445", label: "Special Needs" },
                      { value: "446", label: "Speech Therapist" },
                      { value: "447", label: "Splinting" },
                      { value: "448", label: "Sport" },
                      { value: "449", label: "Statewide And Specia" },
                      { value: "450", label: "STD" },
                      { value: "451", label: "STI" },
                      { value: "452", label: "Stillbirth" },
                      { value: "453", label: "Stomal Care" },
                      { value: "454", label: "Stroke" },
                      { value: "455", label: "Substance Abuse" },
                      { value: "456", label: "Support" },
                      { value: "457", label: "Syringes" },
                      { value: "458", label: "Teeth" },
                      { value: "459", label: "Tenancy Advice" },
                      { value: "460", label: "Terminal Illness" },
                      { value: "461", label: "Therapy" },
                      { value: "462", label: "Transcription" },
                      { value: "463", label: "Translating Services" },
                      { value: "464", label: "Translator" },
                      { value: "465", label: "Transport" },
                      { value: "466", label: "Vertebrae" },
                      { value: "467", label: "Violence" },
                      { value: "468", label: "Vocational Guidance" },
                      { value: "469", label: "Weight" },
                      { value: "470", label: "Welfare Assistance" },
                      { value: "471", label: "Welfare Counselling" },
                      { value: "472", label: "Wheelchairs" },
                      { value: "473", label: "Wound Management" },
                      { value: "474", label: "Young People At Risk" },
                      { value: "475", label: "Further Desc. - Community Health Care" },
                      { value: "476", label: "Library" },
                      { value: "477", label: "Community Hours" },
                      { value: "478", label: "Further Desc. - Specialist Medical" },
                      { value: "479", label: "Hepatology" },
                      { value: "480", label: "Gastroenterology " },
                      { value: "481", label: "Gynaecology" },
                      { value: "482", label: "Obstetrics" },
                      { value: "483", label: "Further Desc. - Specialist Surgical" },
                      { value: "484", label: "Placement Protection" },
                      { value: "485", label: "Family Violence" },
                      { value: "486", label: "Integrated Family Services" },
                      { value: "488", label: "Diabetes Educator" },
                      { value: "489", label: "Kinship Care" },
                      { value: "490", label: "General Mental Health Services" },
                      { value: "491", label: "Exercise Physiology" },
                      { value: "492", label: "Medical Research" },
                      { value: "493", label: "Youth" },
                      { value: "494", label: "Youth Services" },
                      { value: "495", label: "Youth Health" },
                      { value: "496", label: "Child and Family Ser" },
                      { value: "497", label: "Home Visits" },
                      { value: "498", label: "Mobile Services" },
                      { value: "500", label: "Before and/or After " },
                      { value: "501", label: "Cancer Services" },
                      { value: "502", label: "Integrated Cancer Se" },
                      { value: "503", label: "Multidisciplinary Se" },
                      { value: "504", label: "Multidisciplinary Ca" },
                      { value: "505", label: "Meetings" },
                      { value: "506", label: "Blood pressure monit" },
                      { value: "507", label: "Dose administration " },
                      { value: "508", label: "Medical Equipment Hi" },
                      { value: "509", label: "Parenting/Family Support/Education" },
                      { value: "510", label: "Deputising Service" },
                      { value: "513", label: "Cancer Support Groups" },
                      { value: "514", label: "Community Cancer Services" },
                      { value: "530", label: "Disability Care Transport" },
                      { value: "531", label: "Aged Care Transport" },
                      { value: "532", label: "Diabetes Education s" },
                      { value: "533", label: "Cardiac Rehabilitati" },
                      { value: "534", label: "Young Adult Diabetes" },
                      { value: "535", label: "Pulmonary Rehabilita" },
                      { value: "536", label: "Art therapy " },
                      { value: "537", label: "Medication Reviews" },
                      { value: "538", label: "Telephone Counselling" },
                      { value: "539", label: "Telephone Help Line" },
                      { value: "540", label: "Online Service" },
                      { value: "541", label: "Crisis - Mental Health" },
                      { value: "542", label: "Youth Crisis" },
                      { value: "543", label: "Sexual Assault" },
                      { value: "544", label: "GPAH Other" },
                      { value: "545", label: "Paediatric Dermatology" },
                      { value: "546", label: "Veterans Services" },
                      { value: "547", label: "Veterans" },
                      { value: "548", label: "Food Relief/Food/Meals" },
                      { value: "550", label: "Dementia Care" },
                      { value: "551", label: "Alzheimer" },
                      { value: "552", label: "Drug and/or Alcohol Support Groups" },
                      { value: "553", label: "1-on-1 Support /Mentoring /Coaching" },
                      { value: "554", label: "Chronic Disease Management" },
                      { value: "555", label: "Liaison Services" },
                      { value: "556", label: "Walk-in Centre /Non-Emergency" },
                      { value: "557", label: "Inpatients" },
                      { value: "558", label: "Spiritual Counselling" },
                      { value: "559", label: "Women's Health" },
                      { value: "560", label: "Men's Health" },
                      { value: "561", label: "Health Education/Awareness Program" },
                      { value: "562", label: "Test Message" },
                      { value: "563", label: "Remedial Massage" },
                      { value: "564", label: "Adolescent Mental Health Services" },
                      { value: "565", label: "Youth Drop In/Assistance/Support" },
                      { value: "566", label: "Aboriginal Health Worker" },
                      { value: "567", label: "Women's Health Clinic" },
                      { value: "568", label: "Men's Health Clinic" },
                      { value: "569", label: "Migrant Health Clinic" },
                      { value: "570", label: "Refugee Health Clinic" },
                      { value: "571", label: "Aboriginal Health Clinic" },
                      { value: "572", label: "Nurse Practitioner Lead Clinic/s" },
                      { value: "573", label: "Nurse Lead Clinic/s" },
                      { value: "574", label: "Culturally Tailored Support Groups" },
                      { value: "575", label: "Culturally Tailored Health Promotion" },
                      { value: "576", label: "Rehabilitation" },
                      { value: "577", label: "Education Information/Referral" },
                      { value: "580", label: "Social Work" },
                      { value: "581", label: "Haematology" },
                      { value: "582", label: "Maternity Shared Car" },
                      { value: "583", label: "Rehabilitation Servi" },
                      { value: "584", label: "Cranio-sacral Therapy" },
                      { value: "585", label: "Prosthetics & Orthotics" },
                      { value: "589", label: "Home Medicine Review" },
                      { value: "590", label: "GPAH - Medical" },
                      { value: "591", label: "Music Therapy" },
                      { value: "593", label: "Falls Prevention" },
                      { value: "599", label: "Accommodation/Tenancy" },
                      { value: "600", label: "Assess-Skill, Ability, Needs" },
                      { value: "601", label: "Assist Access/Maintain Employ" },
                      { value: "602", label: "Assist Prod-Pers Care/Safety" },
                      { value: "603", label: "Assist-Integrate School/Ed" },
                      { value: "604", label: "Assist-Life Stage, Transition" },
                      { value: "605", label: "Assist-Personal Activities" },
                      { value: "606", label: "Assist-Travel/Transport" },
                      { value: "607", label: "Assistive Equip-General Tasks" },
                      { value: "608", label: "Assistive Equip-Recreation" },
                      { value: "609", label: "Assistive Prod-Household Task" },
                      { value: "610", label: "Behavior Support" },
                      { value: "611", label: "Comms & Info Equipment" },
                      { value: "612", label: "Community Nursing Care" },
                      { value: "613", label: "Daily Tasks/Shared Living" },
                      { value: "614", label: "Development-Life Skills" },
                      { value: "615", label: "Early Childhood Supports" },
                      { value: "616", label: "Equipment Special Assess Setup" },
                      { value: "617", label: "Hearing Equipment" },
                      { value: "618", label: "Home Modification" },
                      { value: "619", label: "Household Tasks" },
                      { value: "620", label: "Interpret/Translate" },
                      { value: "621", label: "Other Innovative Supports" },
                      { value: "622", label: "Participate Community" },
                      { value: "623", label: "Personal Mobility Equipment" },
                      { value: "624", label: "Physical Wellbeing" },
                      { value: "625", label: "Plan Management" },
                      { value: "626", label: "Therapeutic Supports" },
                      { value: "627", label: "Training-Travel Independence" },
                      { value: "628", label: "Vehicle modifications" },
                      { value: "629", label: "Vision Equipment" }
                ].sort((a, b) => a.label.localeCompare(b.label))
            ],
            description: "Select encounter service type. [ValueSet](http://hl7.org/fhir/R4/valueset-service-type.html) 🔗"
        },
        note_type: {
            name: "FHIR Document Type",
            type: "string",
            description: "Require patients to have specific clinical notes of type [ValueSet](https://build.fhir.org/valueset-doc-typecodes.html)"
        },
        enc_min: {
            name: "Min FHIR Encounters",
            type: "number",
            description: "Min number of [FHIR Encounters](https://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-encounter.html) during study period"
        },
        enc_max: {
            name: "Max FHIR Encounters",
            type: "number",
            description: "Max number of [FHIR Encounters](https://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-encounter.html) during study period"
        },
        enc_days_min: {
            name: "Min Duration",
            type: "number",
            description: "Min number of days between first and last encounter"
        },
        doc_variables: {
            name: "Doc Variables",
            type: "checklist",
            items: [
                { label: "biopsy / kidney", value: { name: "kidney", value: "2.16.840.1.113762.1.4.1222.864" }},
                { label: "biopsy / skin", value: { name: "skin", value: "2.16.840.1.113762.1.4.1222.867" }},
                { label: "biopsy / lung", value: { name: "lung", value: "2.16.840.1.113883.3.1434.1011" }},
                { label: "biopsy / bone", value: { name: "bone", value: "2.16.840.1.113762.1.4.1222.870" }},
                { label: "biopsy / muscle", value: { name: "muscle", value: "2.16.840.1.113762.1.4.1222.868" }},
            ]
        },
        proc_variables: {
            name: "FHIR Procedure",
            type: "checklist",
            items: [
                { label: "dialysis / services", value: { name: "services", value: "2.16.840.1.113883.3.464.1003.109.12.1013" }},
                { label: "surgery / other_major", value: { name: "other_major", value: "2.16.840.1.113883.3.464.1003.198.12.1075" }}
            ]
        },
        lab_variables: {
            name: "FHIR Observation Laboratory",
            type: "checklist",
            items: [
                { label:"cbc / with_diff", value: { name: "with_diff", value: "1.3.6.1.4.1.6997.4.1.2.271.13.38167.1.1.999.594" }},
                { label:"cmp / comprehensive", value: { name: "comprehensive", value: "2.16.840.1.113762.1.4.1078.867" }},
                { label:"gfr / egfr", value: { name: "egfr", value: "2.16.840.1.113762.1.4.1078.397" }},
                { label:"lft / function", value: { name: "function", value: "2.16.840.1.113762.1.4.1078.867" }},
                { label:"lft / ggt", value: { name: "ggt", value: "2.16.840.1.113762.1.4.1222.806" }},
                { label:"lft / pt", value: { name: "pt", value: "2.16.840.1.113883.3.3616.200.110.102.5037" }},
                { label:"lft / inr", value: { name: "inr", value: "2.16.840.1.113883.3.117.1.7.1.213" }},
                { label:"creatinine / serum_cr", value: { name: "serum_cr", value: "2.16.840.1.113762.1.4.1146.2206" }},
                { label:"creatinine / urine_cr", value: { name: "urine_cr", value: "2.16.840.1.113762.1.4.1178.87" }},
                { label:"creatinine / urine_alb_cr_ratio", value: { name: "urine_alb_cr_ratio", value: "2.16.840.1.113883.3.6929.3.1007" }},
                { label:"creatinine / urine_protein_cr_ratio", value: { name: "urine_protein_cr_ratio", value: "2.16.840.1.113762.1.4.1222.790" }},
                { label:"creatinine / blood_cr", value: { name: "blood_cr", value: "2.16.840.1.113762.1.4.1222.111" }},
                { label:"autoimmune / serum_rf", value: { name: "serum_rf", value: "2.16.840.1.113762.1.4.1222.812" }},
                { label:"autoimmune / blood_esr", value: { name: "blood_esr", value: "2.16.840.1.113762.1.4.1222.1609" }},
                { label:"autoimmune / crp", value: { name: "crp", value: "2.16.840.1.113762.1.4.1146.1933" }},
                { label:"autoimmune / tsh", value: { name: "tsh", value: "2.16.840.1.113762.1.4.1146.2156" }},
                { label:"autoimmune / t3", value: { name: "t3", value: "2.16.840.1.113762.1.4.1078.864" }},
                { label:"autoimmune / t4", value: { name: "t4", value: "2.16.840.1.113762.1.4.1078.865" }},
                { label:"diabetes / screening", value: { name: "screening", value: "2.16.840.1.113762.1.4.1221.122" }},
                { label:"diabetes / glucose_test", value: { name: "glucose_test", value: "2.16.840.1.113762.1.4.1045.134" }},
            ]
        },
        rx_variables: {
            name: "FHIR MedicationRequest",
            type: "checklist",
            items: [
                { label: "immunosuppressive / everolimus", value: { name: "everolimus", value: "2.16.840.1.113762.1.4.1260.499" }},
                { label: "immunosuppressive / drugs", value: { name: "drugs", value: "2.16.840.1.113762.1.4.1219.192" }},
                { label: "immunosuppressive / systemic_therapy", value: { name: "systemic_therapy", value: "2.16.840.1.113883.3.666.5.803" }},
                { label: "immunosuppressive / immune_modulators", value: { name: "immune_modulators", value: "2.16.840.1.113762.1.4.1248.124" }},
                { label: "immunosuppressive / coricosteroids_systemic", value: { name: "coricosteroids_systemic", value: "2.16.840.1.113883.3.3616.200.110.102.2061" }},
                { label: "cancer / chemo_advanced", value: { name: "chemo_advanced", value: "2.16.840.1.113883.3.7643.2.1046" }},
                { label: "cancer / checkpoint", value: { name: "checkpoint", value: "2.16.840.1.113762.1.4.1133.6" }},
                { label: "cancer / keytruda", value: { name: "keytruda", value: "2.16.840.1.113762.1.4.1260.496" }},
                { label: "cancer / ade_neutropenia", value: { name: "ade_neutropenia", value: "2.16.840.1.113883.3.526.3.1538" }},
                { label: "antibiotics / any", value: { name: "any", value: "2.16.840.1.113762.1.4.1078.849" }},
                { label: "antibiotics / systemic", value: { name: "systemic", value: "2.16.840.1.113762.1.4.1133.6" }},
                { label: "immunocompromised / therapies", value: { name: "therapies", value: "2.16.840.1.113762.1.4.1235.212" }},
                { label: "diabetes / drugs", value: { name: "drugs", value: "2.16.840.1.113762.1.4.1190.58" }},
                { label: "htn / drugs", value: { name: "drugs", value: "2.16.840.1.113883.3.600.1476" }},
                { label: "diuretics / loop", value: { name: "loop", value: "2.16.840.1.113762.1.4.1078.898" }},
                { label: "diuretics / potassium", value: { name: "potassium", value: "2.16.840.1.113762.1.4.1213.41" }},
                { label: "diuretics / thiazide", value: { name: "thiazide", value: "2.16.840.1.113762.1.4.1078.8" }},
            ]
        },
        dx_variables: {
            name: "FHIR Condition",
            type: "checklist",
            items: [
                { label: "cancer / skin", value: { name: "skin", value: "2.16.840.1.113883.3.526.3.1010" }},
                { label: "cancer / melanoma", value: { name: "melanoma", value: "2.16.840.1.113883.3.526.3.1010" }},
                { label: "cancer / melanoma_malignant", value: { name: "melanoma_malignant", value: "2.16.840.1.113883.3.1434.1038" }, description: "2.16.840.1.113883.3.1434.1038"},
                { label: "cancer / melanoma_malignant", value: { name: "melanoma_malignant", value: "2.16.840.1.113883.3.464.1003.108.11.1018" }, description: "2.16.840.1.113883.3.464.1003.108.11.1018"},
                { label: "cancer / sarcoma", value: { name: "sarcoma", value: "2.16.840.1.113883.3.526.3.1010" }},
                { label: "cancer / squamous", value: { name: "squamous", value: "2.16.840.1.113883.3.526.3.1010" }},
                { label: "kidney / condition", value: { name: "condition", value: "2.16.840.1.113883.17.4077.3.2028" }},
                { label: "kidney / renal_disease", value: { name: "renal_disease", value: "2.16.840.1.113762.1.4.1029.335" }},
                { label: "kidney / esrd", value: { name: "esrd", value: "2.16.840.1.113762.1.4.1235.172" }},
                { label: "kidney / ckd", value: { name: "ckd", value: "2.16.840.1.113762.1.4.1078.114" }},
                { label: "kidney / dialysis", value: { name: "dialysis", value: "2.16.840.1.113762.1.4.1078.342" }},
                { label: "kidney / nephrotic_syndrome", value: { name: "nephrotic_syndrome", value: "2.16.840.1.113883.3.464.1003.109.12.1018" }},
                { label: "autoimmune / inflammatory", value: { name: "inflammatory", value: "2.16.840.1.113883.3.3157.1834" }},
                { label: "autoimmune / ibd", value: { name: "ibd", value: "2.16.840.1.113762.1.4.1078.879" }},
                { label: "autoimmune / crohns", value: { name: "crohns", value: "2.16.840.1.113762.1.4.1034.576" }},
                { label: "autoimmune / arthritis_ra", value: { name: "arthritis_ra", value: "2.16.840.1.113762.1.4.1222.651" }, description: "2.16.840.1.113762.1.4.1222.651"},
                { label: "autoimmune / arthritis_ra", value: { name: "arthritis_ra", value: "2.16.840.1.113762.1.4.1222.81" }, description: "2.16.840.1.113762.1.4.1222.81" },
                { label: "autoimmune / lupus", value: { name: "lupus", value: "2.16.840.1.113883.3.464.1003.117.12.1010" }},
                { label: "immunocompromised / any", value: { name: "any", value: "2.16.840.1.113883.3.666.5.1940" }, description: "2.16.840.1.113883.3.666.5.1940" },
                { label: "immunocompromised / any", value: { name: "any", value: "2.16.840.1.113762.1.4.1235.212" }, description: "2.16.840.1.113762.1.4.1235.212" },
                { label: "infection / bacterial", value: { name: "bacterial", value: "2.16.840.1.113762.1.4.1200.288" }},
                { label: "infection / pna", value: { name: "pna", value: "2.16.840.1.113762.1.4.1078.738" }},
                { label: "infection / cmv", value: { name: "cmv", value: "2.16.840.1.113762.1.4.1146.2234" }, description: "2.16.840.1.113762.1.4.1146.2234" },
                { label: "infection / cmv", value: { name: "cmv", value: "2.16.840.1.113762.1.4.1146.2233" }, description: "2.16.840.1.113762.1.4.1146.2233" },
                { label: "infection / rsv", value: { name: "rsv", value: "2.16.840.1.113762.1.4.1078.754" }},
                { label: "infection / influenza", value: { name: "influenza", value: "2.16.840.1.113762.1.4.1078.747" }},
                { label: "infection / shingles", value: { name: "shingles", value: "2.16.840.1.113762.1.4.1222.1478" }},
                { label: "infection / hepatitis_b", value: { name: "hepatitis_b", value: "2.16.840.1.113883.3.464.1003.110.12.1025" }},
                { label: "infection / hepatitis_c", value: { name: "hepatitis_c", value: "2.16.840.1.113762.1.4.1222.30" }},
                { label: "heart / cardiomyopathy", value: { name: "cardiomyopathy", value: "2.16.840.1.113762.1.4.1222.579" }},
                { label: "heart / attack", value: { name: "attack", value: "2.16.840.1.113883.3.666.5.3011" }},
                { label: "heart / failure", value: { name: "failure", value: "2.16.840.1.113762.1.4.1222.1543" }},
                { label: "heart / cohort", value: { name: "cohort", value: "2.16.840.1.113762.1.4.1182.308" }},
                { label: "htn / essential", value: { name: "essential", value: "2.16.840.1.113883.3.464.1003.104.12.1011" }},
                { label: "htn / any", value: { name: "any", value: "2.16.840.1.113762.1.4.1251.12" }},
                { label: "htn / hypertensive_ckd", value: { name: "hypertensive_ckd", value: "2.16.840.1.113883.3.464.1003.109.12.1017" }},
                { label: "diabetes / disorder", value: { name: "disorder", value: "2.16.840.1.113762.1.4.1219.35" }},
                { label: "diabetes / preexisting", value: { name: "preexisting", value: "2.16.840.1.113883.3.464.1003.198.12.1075" }},
                { label: "diabetes / complications", value: { name: "complications", value: "2.16.840.1.113762.1.4.1222.1537" }},
                { label: "diabetes / t2d_related_dx", value: { name: "t2d_related_dx", value: "2.16.840.1.113762.1.4.1078.440" }},
                { label: "diabetes / diabetic_nephropathy", value: { name: "diabetic_nephropathy", value: "2.16.840.1.113883.3.464.1003.109.12.1004" }},
                { label: "diabetes / diabetic_ckd", value: { name: "diabetic_ckd", value: "2.16.840.1.113762.1.4.1078.124" }},
            ]
        }
    }
}
