openapi: "3.0.1"
info:
  title: "CumulusAggregatorDashboardApi-dev"
  version: "1.0"
servers:
- url: "https://url"
  variables:
    basePath:
      default: "dev"
paths:
  /metadata/{site}/{study}/{subscription}:
    get:
      parameters:
      - name: "study"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "subscription"
        in: "path"
        required: true
        schema:
          type: "string"
    options:
      parameters:
      - name: "study"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "subscription"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /metadata:
    get: {}
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /chart-data/{subscription_name}:
    get:
      parameters:
      - name: "subscription_name"
        in: "path"
        required: true
        schema:
          type: "string"
    options:
      parameters:
      - name: "subscription_name"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /study-periods/{site}:
    get:
      parameters:
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
    options:
      parameters:
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /subscriptions:
    get: {}
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /metadata/{site}/{study}:
    get:
      parameters:
      - name: "study"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
    options:
      parameters:
      - name: "study"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /metadata/{site}:
    get:
      parameters:
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
    options:
      parameters:
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /study-periods/{site}/{study}:
    get:
      parameters:
      - name: "study"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
    options:
      parameters:
      - name: "study"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "site"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /study-periods:
    get: {}
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components: {}
