import Highcharts from "highcharts/esm/highcharts.js"
import "highcharts/esm/highcharts-more.js"
import "highcharts/esm/highcharts-3d.js"
import "highcharts/esm/modules/exporting.js"
import "highcharts/esm/modules/offline-exporting.js"
import "highcharts/esm/modules/export-data.js"
import "highcharts/esm/modules/no-data-to-display.js"
import "highcharts/esm/modules/pattern-fill.js"
import "highcharts/esm/modules/annotations.js"
import "highcharts/esm/modules/accessibility.js"
import "highcharts/esm/modules/drilldown.js"
import "highcharts/esm/modules/coloraxis.js"
// import "highcharts/esm/modules/cylinder.js"
// import "highcharts/esm/modules/funnel.js"
// import "highcharts/esm/modules/heatmap.js"
// import "highcharts/esm/modules/treemap.js"
// import "highcharts/esm/modules/boost.js"
// import "highcharts/esm/modules/venn.js"

export type * from "highcharts/esm/highcharts.js"
export default Highcharts
