
name: Backend Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      
      - uses: actions/checkout@v3
    
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npx ts-mocha --version
      - run: npx ts-node --version
      - run: pwd
      - run: ls -l
      - run: npm ci
      - run: npm run build
      - run: npm run test

