
name: Backend Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    branches: [ "*" ]

jobs:
  build:
    
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      
      - uses: actions/checkout@v3
    
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci --legacy-peer-deps

      - run: npm run test:server
      # - run: ./node_modules/.bin/mocha -r dotenv/config --exit -t 5000

