
name: Backend Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      
      - uses: actions/checkout@v3
    
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
        env:
          NODE_ENV: "test"
          HOST: "0.0.0.0"
          PORT: 0
          THROTTLE: 0
          VERBOSE: "false"
          MAILGUN_API_KEY: "whatever"
          MAILGUN_DOMAIN: "whatever"
          APP_EMAIL_FROM: "test@cumulus.org"
          CUMULUS_ADMIN_EMAIL: "test@cumulus.org"
          REGIONAL_CLUSTER_EMAIL: "test@cumulus.org"
          DATABASE_URL: "postgres://postgres:cumulus_test_db_password@localhost:5455/cumulus_test"
          DB_HOST: "localhost"
          DB_PORT: 5455
          DB_USER: "postgres"
          DB_PASS: "cumulus_test_db_password"
          DB_DATABASE: "cumulus_test"
          DB_SEED: "../test/test-seeds.js"
          LOG_SQL: "false"
          DB_SYNC: "force"
          DB_DOCKER_CONTAINER: "cumulus_test"
          DB_DOCKER_DATA_DIR: ""
          DB_SSL: "false"
          DEBUG: "*"

      - run: npm ci --legacy-peer-deps

      - run: npm run test:server
      # - run: ./node_modules/.bin/mocha -r dotenv/config --exit -t 5000

