name: CI

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [ 22.17.0 ]

    steps:
      
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm run test

  bdf-validation:
    name: BDF validation
    uses: ARPA-H-BDF/bdfkb-schema/.github/workflows/ci-validate.yaml@6afe39430894512131b7f86f75ac165e8db65551 # main
    with:
      python-version: '3.11'